### ISSUE TITLE
Using environment variables to control minimum instances

### ISSUE THREAD

**Issue by aramael** [firebase/firebase-functions#1044]
### [REQUIRED] Version info
**node:** v16.11.1

**firebase-functions:** 3.18.1

**firebase-tools:** 10.2.1

**firebase-admin:** 10.0.2

### [REQUIRED] Test case
Unapplied `.env` environment variables during function deployment; or unused environment variables from path when deploying function to calculate minimum instance count.

It seems some variables like `GCLOUD_PROJECT` and `FIREBASE_CONFIG ` are available to the functions when evaluating `.runWith()` configuration parameters, but passed parameters through `.env` files or from the console are not passed as might be expected, based on [sample provided](https://github.com/firebase/functions-samples/blob/a23a172de14f9e762667f3e318437293c2567c2b/quickstarts/runtime-options/functions/index.js#L15-L26) in the [documentation](https://firebase.google.com/docs/functions/manage-functions#min-max-instances).

### [REQUIRED] Steps to reproduce

1. Create a `.env` file
```Shell
DOTENV_MIN_INSTANCES_FLAG=1
```

2. Create two functions endpoint with a HTTP trigger
```node
exports.myFirstMockEndpoint = functions
    .runWith({
      minInstances: process.env.DOTENV_MIN_INSTANCES_FLAG ? 5 : 0,
    })
    .https.onRequest((req, res) => {
      // render some html
    });

exports.mySecondMockEndpoint = functions
    .runWith({
      minInstances: process.env.GCLOUD_PROJECT === "<my-gcloud-project>" ? 2 : 0,
    })
    .https.onRequest((req, res) => {
      // render some html
    });

exports.myThirdMockEndpoint = functions
    .runWith({
      minInstances: process.env.CONSOLE_MIN_INSTANCES_FLAG ? 3 : 0,
    })
    .https.onRequest((req, res) => {
      // render some html
    });
```

3. Deploy the function
```
export CONSOLE_MIN_INSTANCES_FLAG=1 && firebase deploy --only functions
```

4. Navigate to the function detail for `myFirstMockEndpoint`, `mySecondMockEndpoint`, and `myThirdMockEndpoint` on GCP. View *details* tab, check *Minimum instances*

### [REQUIRED] Expected behavior
Expect `myFirstMockEndpoint` *Minimum instances* to be **5**, `mySecondMockEndpoint` *Minimum instances* to be **2**, and  `myThirdMockEndpoint ` *Minimum instances* to be **3**

### [REQUIRED] Actual behavior
`myFirstMockEndpoint` has **0** *Minimum instances*, `mySecondMockEndpoint ` has **2** *Minimum instances*, and  `mySecondMockEndpoint ` has **0** *Minimum instances*.

### Were you able to successfully deploy your functions?
Yes, the functions deployed successfully, though with incorrect parameters.

***Submitter Note:*** I know this might be an incorrect bug report as the functions did deploy but are perhaps not working as expected, but a previous bug #968 was addressed when similar expected and actual behaviors were encountered, so I'm submitting anyway. If theres a more appropriate venue, please direct me to where I should file the bug.

**Comment by taeold** [comment]
Hi @aramael and @mauriceackel - thanks for reaching out.

As both of you have already found out, we are intentionally not including user-defined environment variables when parsing your source code to discover your functions. This limits their use when compared to functions config.

We are preparing something new that digs into exactly this problem -stay tuned. Until then, I'd suggest that you continue to rely on functions config if need environment-aware logic when deploying your functions.

**Comment by mauriceackel** [comment]
Hi @taeold and thanks for the response!

I'm curious as to why this was designed in this way. Especially as it impacts some important functionality in my opinion.

For example, I have a config.js where I load and parse all my environment variables and finally export them. In this config.js file I want to en sure that all environment variables are actually set. To do this, I check if they are defined and if not, I throw an error. Now, as I was using function config, this worked fine and I was able to deploy my functions.. Using .env however breaks this functionality as none of my user-defined variables are defined at deploy time.

Also I find it a bit confusing that I can use process.env in some parts of my code but not in other parts.. If someone does not know the inner workings of how functions are deployed this is hard to understand. Matters get worse as this is not documented as far as I can tell and moreover, just before the deploy error is shown, the cli prints the message that the variables from .env files were loaded. This makes it really hard to debug and understand.

Personally, I would love to have the .env files parsed at deployment time as well so that I don't have to deal with multiple config files and have to know in which part of my code I can use which. I believe this would result in a much smoother, more straightforward development experience.

At least this is my opinion on it. I would love to hear more from other developers and @aramael yourself.

**Comment by SrBrahma** [comment]
@taeold Printing process.env is returning undefined on emulator. This didn't happen before. I believe an update did this change. I don't want to create an issue because I think I may be missing something that I should know.

**Comment by uvesten** [comment]
Could you at least update the documentation at https://firebase.google.com/docs/functions/config-env as long as the `.env` file environment handling is broken (yes, **broken**. There is no way someone would expect environment variables to _not_ be available until an arbitrary point in code execution) so that developers don't get the false impression that `functions.config()` and `.env` is equivalent? 

I just wasted way more time than I'd like to share porting our configs to `.env` for better developer ergonomics, only to realize I have to revert to `functions.config()` again. Sigh.

**Comment by DibyodyutiMondal** [comment]
> we are intentionally not including user-defined environment variables when parsing your source code to discover your functions. This limits their use when compared to functions config.
> 
> We are preparing something new that digs into exactly this problem -stay tuned.

@taeold Any updates on this?

**Comment by inlined** [comment]
See https://github.com/firebase/firebase-functions/issues/1084 for our plans around this area.

**Comment by trex-quo** [comment]
It seems environment variables that are only needed at runtime break deployments as well due to the way that Firebase Functions parse function triggers. I don't believe we are able to deploy any functions that reference environment variables from the .env file in general. Is this the case? 

```
i  functions: Loaded environment variables from .env, .env.staging.

Error: Error occurred while parsing your function triggers.

Error: The {service} client requires a token: `init(token)`
```

**Comment by nickjuntilla** [comment]
We just switched everything over the .env and now you guys are saying it doesn't work? Why does the documentation recommend everyone to use .env?

From: https://firebase.google.com/docs/functions/config-env

```
You can choose between file-based configuration of environment variables (**recommended**) or runtime environment configuration with the Firebase CLI and functions.config. Both approaches are described in this guide.
```

You guys are recommending something that doesn't work at all. This makes no sense.

**Comment by Franco-Alejandro** [comment]
All of a sudden our .env variables show up as undefined... I don't understand why this issue is closed. As @nickjuntilla has pointed out, this is still recommended on the docs. I don't understand how a "feature that compliments .env files" will fix this when the issue really seems related to how the feature itself (.env files) works 🤔 

If someone could shed some light on how to proceed, that'd be great.... for now we're reverting everything back to config 😞

**Comment by kozzztya** [comment]
I'm using a workaround for this. I created a buildConfig.ts.template file and update buildConfig.ts before deploy based on env vars `API_MIN_INSTANCES=2 yarn build:config:update && firebase deploy --only functions`.

```
export const buildConfig = {
  apiMinInstances: $API_MIN_INSTANCES,
}
```

```
import { buildConfig } from './common/buildConfig';

export const api = onRequest(
  {
    region: 'europe-central2',
    minInstances: buildConfig.apiMinInstances,
    secrets,
    cors: false,
  },
  app
);

```

**Comment by DibyodyutiMondal** [comment]
It's running the code at build time in order to analyse the exports. Said analysis will determine what functions are supposed to be deployed, what region, what secrets, etc etc. 

The function handlers will never run at build time, because that's a callback.

But the declarations to firebase-functions will be invoked because they are direct function calls. It's javascript.

The alternative to code analysis would necessarily be for us to create a manifest file like firebase.json, but just for functions, which I assume the firebase team ruled out when firebase functions was being conceptualized
