### ISSUE TITLE
Unable to use .env variable in functions for database.instance()

### ISSUE THREAD

**Issue by danielluca** [firebase/firebase-functions#1058]
### Version info

**node:** 16.14.0

**firebase-functions:** 3.18.1

**firebase-tools:** 10.2.2

**firebase-admin:** 10.0.2

### Test case

```js
const myFunction = functions
  .runWith({
    vpcConnector: 'static-vpc-connector',
    vpcConnectorEgressSettings: 'ALL_TRAFFIC',
  })
  .region('europe-west3')
  .database
  .instance(process.env.MY_INSTANCE)
  .ref('/some/{ref}')
  .onCreate(async (snapshot, context) => {}
```

### Expected behavior

Function should use the .env variable set in .env file.

### Actual behavior

If I set the instance without a .env variable, the function can be deployed.
If I set the instance with a .env, I get an error.

### Were you able to successfully deploy your functions?

```bash
i  functions: cleaning up build files...
Error: There was an error deploying functions
```

**Comment by taeold** [comment]
Other issues that touches on this problem:

https://github.com/firebase/firebase-tools/issues/4361
https://github.com/firebase/firebase-functions/issues/1044

Pasting a response I posted in another issue:

> As both of you have already found out, we are intentionally not including user-defined environment variables when parsing your source code to discover your functions. This limits their use when compared to functions config.
>
> We are preparing something new that digs into exactly this problem -stay tuned. Until then, I'd suggest that you continue to rely on functions config if need environment-aware logic when deploying your functions.

Since this is a common point of confusion, I'm going to try to consolidate our response in a single issue. Arbitrary going to pick the earliest reported issue (https://github.com/firebase/firebase-functions/issues/1044) as our single source of truth. Let's continue our discussion there.

**Comment by inlined** [comment]
See https://github.com/firebase/firebase-functions/issues/1084 for our plans around this area.
