### ISSUE TITLE
Cloud Firestore triggers for v2 functions

### ISSUE THREAD

**Issue by dahu33** [firebase/firebase-functions#1213]
Please add Cloud Firestore triggers for v2 functions in the SDK, this is really missing.

**Comment by bsmrto** [comment]
Currently available Cloud Functions triggers
Cloud Functions v2 supports the following Firebase background triggers:

Firebase Realtime Database Cloud Storage Firebase Alerts Pub/Sub Callables Cloud Tasks HTTP
Cloud Functions v2 does not currently support the following triggers:

Cloud Firestore Firebase Authentication Google Analytics Scheduled functions Firebase Remote Config Firebase Test Lab

**Comment by taishi55** [comment]
Please add firebase auth as well.

V2 functions support firebase identity, but not a regular auth.

**Comment by n0thingness** [comment]
@taeold Is there any timeline on this feature?

**Comment by nicksav** [comment]
Need update guys. Taking too long for such a critical feature.

**Comment by rodneyrd** [comment]
up :)

**Comment by cyberpwnn** [comment]
I tried to implement a deployed for the Java firebase admin sdk and the google cloud functions v2 sdks (firebase is just a thin wrapper). And my god, functions v2 is so overcomplicated for no reason. You need to use eventarc to link (probably pubsub) events to a cloud function, but there arent any events in eventarc that support firestore. The only way to do it is to turn on audit logging for firestore, then make a pubsub listener for the writes to the audit log then somehow connect that with eventarc.

It's so stupid, I have no idea why they released v2 functions before they had everything working, but my point here is that firebase cant really do anything until gcp fixes v2 functions and actually adds the event sources they claim to now have. Again, firebase is a thin wrapper around google services. And after trying to implement it, I've found that its actually not possible yet because of gcp v2 functions.

**Comment by patrikjuvonen** [comment]
Should have been resolved via #1358 on v4.3.0 release
