### ISSUE TITLE
[FR] Allow upper-case letters and underscores in v2 function names

### ISSUE THREAD

**Issue by akauppi** [firebase/firebase-functions#1279]
>Note: This is more Cloud Functions v2 beta feedback than a bug (though it might be that as well). I don't really know, how this is *intended* to work. The documentation only covers Common-JS like module definitions.

If this is in the wrong place, please advice where it should be and I'll happily move over.

### [REQUIRED] Version info

**node:** n/a

**firebase-functions:** 4.0.1

**firebase-tools:** 11.15.0

**firebase-admin:** n/a

### [REQUIRED] Test case

Before transitioning to Cloud Functions v2, I had a function called `metricsAndLogProxy_v0`. I declare my Cloud Functions as an ES module. With 'v2', function names must be in "lower case, number or dashes". 

I went for `metrics-and-log-proxy-v0`.

How to declare that as an ESM export?

```
// Doesn't compile (obvious)
export const "metrics-and-logging-proxy-v0" = ...
```

**Edit:** <strike>This does compile. Up to the authors to judge, whether it's clumsy:

```
export const metrics = { ["and-logging-proxy-v0"]: metricsAndLoggingProxy_v0 }
```
</strike>

```
export const metrics = { and: { logging: { proxy: { v0: metricsAndLoggingProxy_v0 }}}}
```

>Note: [Coming soon...](https://cloud.google.com/functions/docs/concepts/version-comparison#coming_soon_in_2nd_gen) mentions:
>> Support for using capital letters in function names.

Remains to be seen, whether also underscores will eventually be supported. Having capitals will help. I just wish that ES module use case is considered in making the v2 documentation (and internal test cases).

### [REQUIRED] Expected behavior

I can use ES modules for declaring my Cloud Function v2 callables.

### [REQUIRED] Actual behavior

I can, but it's a) undocumented, b) edge cases may not work.

### Were you able to successfully deploy your functions?

Yes. I can use whatever names, until v2 is stable.

**Comment by inlined** [comment]
Unfortunately GCF 2nd gen is built on Cloud Run, which is based on the KNative open source spec. KNative uses service names as parts of DNS hostnames, which puts a lot of restrictions on the characters that can be used (no underscores or capital letters). As it stands, those requirements have back-propagated all the way to Cloud Functions for Firebase.

We have had two ideas to improve this:
1. `firebase-tools` can magically transform capital letters and underscores to dashes.
2. We can beg Cloud to do the same in their backend

Because, as you've discovered, dashes already mean something significant in Cloud Functions for Firebase (grouping functions, where "." wasn't allowed) it could get really messy if we overload "-" to mean more things in Cloud Functions for Firebase. Therefore we're asking GCF to accept all v1 characters and do the transformation to the Run service name themselves. FWIW they agree.

So for the meantime, I'd recommend just using alllowercaselettersforthewholefunction and we'll release support for better characters as soon as we have it.

**Comment by akauppi** [comment]
Thanks for the background, @inlined .

As a Firebase developer, I'd be fully ok also with the 1st option: translating `myNiceFunction` to `my-nice-function` (and maybe changing '_' to '-' as well?).

Software is all about abstractions and adaptation, I'm sure we developers would understand, and this change would already reduce/remove surprises about how to export our functions.

I'm generally rather pleased in how Firebase v2 is getting us closer to GCP, without burdening with all its details. This seems like the right route, and such translations don't need to be treated as "magic" - as you state - but simply documented.

```
export const metrics = { and: { logging: { proxy: { v0: metricsAndLoggingProxy_v0 }}}}
```

```
export { metricsAndLoggingProxyV0 }
```

**Comment by inlined** [comment]
```
p.s. There's also a third option: just (documented, not magically..) lowercasing any exports. This would allow the source code to be clean, with the slight burden of alllowercase only in the operations, where it may hurt less... (I will regret suggesting this!!) ;)
```

But then, of course, which format shows up in `--only`?

**Comment by anothermh** [comment]
Is there an official [issue](https://issuetracker.google.com/) for this feature that can be tracked? Or is there any other update on the progress for completing this feature?

**Comment by willbattel** [comment]
It has been some time since the last update on this, at least as far as I can find. What is the guidance for developers wanting to migrate 1st Gen functions that follow the `camelCaseFunctionName_vN` naming pattern described by the OP?

Would it be best if we changed everything over to the `lower-case-with-dashes-vN` pattern? In that case, we'd need to update our client apps to use the new 2nd Gen callable function name, and leave the 1st Gen variants active for some time for legacy client compatibility during a transition period.

**Comment by inlined** [comment]
Sorry we didn't open this bug. You've been able to use upper-case letters and underscores since we went GA at I/O

**Comment by cedvdb** [comment]
Is there any documentation on what character can be used ?

I've read a comment that says you can somehow export an object containing nested functions like so
  
```
export const accountContext = {
   onIdentityVerificationAccepted: onUpdate(...)
}
```

then the name will be accountContext.onIdentityVerificationAccepted.

Is that correct ? I'm a bit doubtful firebase would check inside the object.

**Comment by ciriousjoker** [comment]
@tylerpalmerdev In my case I was on an old version of firebase-tools, which not only broke the function names of this issue, but also `onScheduled` wasn't found at all when trying to deploy those functions.

**Comment by jko206** [comment]
I, too, started seeing `Invalid function id: mockWorkflow v2 function name(s) can only contain lower case letters, numbers, hyphens, and not exceed 62 characters in length` after switching from one machine to another. Both Macbooks, but the former was Intel and the latter M1, if this matters at all. 

Tried updating Firebase CLI tool, but that didn't do the job. Can anyone shed light on what's going on?

**Comment by amit20897** [comment]
I'm able to start the deployment of a function with uppercase letters but the deployment fails, because the container can't start, when I change the function name to lowercase letters only (same code) all is good.
https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start

**Comment by MorganTrudeau** [comment]
For me I only get this error on node 18. On node 16 I can deploy with camelCase.
