### ISSUE TITLE
Console changes (memory/timeoutSeconds) not honored on next deploy

### ISSUE THREAD

**Issue by dperezrada** [firebase/firebase-functions#1311]
### [REQUIRED] Version info

**node:** 
v14.19.1

**firebase-functions:**
4.0.2

**firebase-tools:**
11.10.0

**firebase-admin:**
10.3.0
### [REQUIRED] Test case
We bump from 3.22.0 to version 4.0.2, and now it's resetting the memory/timeoutSeconds/connection for 1st gen cloud functions when you didn't define it in code with `runWith`.

### [REQUIRED] Steps to reproduce
* deploy a function without `runWith`
* edit function in console memory to `2GB` timeoutSeconds to `120`
* deploy the same function

### [REQUIRED] Expected behavior
Keep the `2GB` and `120s` timeout

### [REQUIRED] Actual behavior
Memory is reset to `256MB` and timeoutSeconds to `60`

### Were you able to successfully deploy your functions?
Yes. No error.

**Comment by colerogers** [comment]
Hi @dperezrada thanks for opening your first issue here! 

As you've found out, we changed the behavior of how function deploys work with the v4 sdk (since it is a breaking change). If you want to keep the previous behavior, you'd need to set `preserveExternalChanges` to `true` as documented here - https://firebase.google.com/docs/functions/manage-functions#set_runtime_options

**Comment by dperezrada** [comment]
Thanks for the response.
We read the changelog before making the update, but the [release does not mention](https://github.com/firebase/firebase-functions/releases/tag/v4.0.0) the `preserveExternalChanges`. 
If possible edit the changelog, to prevent others from having the same issue. Thanks.

**Comment by taeold** [comment]
@dperezrada Thank you for the feedback and sorry we missed documenting the change. Updated the release not as suggested:

https://github.com/firebase/firebase-functions/releases/tag/v4.0.0
