### ISSUE TITLE
Random CORS Errors in Firebase functions v2 (Callable functions)

### ISSUE THREAD

**Issue by JaydipKalkani** [firebase/firebase-functions#1344]
### Related issues
https://github.com/firebase/firebase-functions/issues/1128

### [REQUIRED] Version info

**node:**
v18.13.0

**firebase-functions:**
4.1.1

**firebase-tools:**
11.21.0

**firebase-admin:**
11.3.0

### [REQUIRED] Test case

Functions code
```
// --- get individual data
export async function getIndividualData(context: any) {
  try {
    let indData = {
      firstName: "Abc",
      lastName: "Xyz"
    } // Replaced actual db read code with sample data to reduce complexity

    let response: any = {
      success: 1,
      message: "success",
      data: indData,
    };

    return response;
  } catch (error) {
    throw new functions.https.HttpsError(error.message, "unknown");
  }
}

// --- get individual data
exports.getindividualdata = functions.https.onCall(
  { cors: true },
  getIndividualData
);
```

Client code
```
async postToCloudFn() {
  // --- get current user auth token
  let token = "someValidClientToken"
  
  // --- prepare headers
  let headers = {
    Authorization: `Bearer ${token}`
  };
  
  // --- prepare server URL to send request to
  let url = "https://getindividualdata-randomchars-uc.a.run.app"
  
  return this.http.post(url, { data: {a: "b"} }, { headers }).toPromise(); // here http refers to Angular HttpClient
}
```

### [REQUIRED] Steps to reproduce
This is the main pain point of this bug report. It is a transient bug and repro of the bug is hard. Still mentioning the steps I believe should work/
- Deploy a v2 function "getindividualdata".
- Create basic Angular project, and call the function using HttpClient (for reasons). That means I am following the guidelines mentioned [here](https://firebase.google.com/docs/functions/callable-reference)
- Try running your client code and it works fine as you expect.
- Now, deploy your client app, use by multiple users and you'll get CORS error randomly on some requests while some requests will work just fine. The ratio of success vs CORS error is approx. 100:5 maybe. Saying based on my error reports I get from my production app users.

### [REQUIRED] Expected behavior

No CORS error.

### [REQUIRED] Actual behavior

Getting a CORS error randomly for production users.

### Were you able to successfully deploy your functions?

Yes, Deployment succeeds without any error.

**Comment by taeold** [comment]
Hi @JaydipKalkani!

As expected, I'm having difficult time reproducing the error - as you say, if the error is "random" I'd expect it to be hard to reproduce for you as well.

One of the issue I've noticed in the past is that CORS error sometimes doesn't actually means you have issues with your CORS setting. It actually means that the HTTP endpoint didn't responds to OPTIONS request (e.g. returned 404 because function isn't available or responding). Confusingly, this is reported as "CORS" issue on the client's browser.

I'm wondering how you were able to gather statistics about the ratio of CORS vs non-CORS issues. Some possible cause I can think of when your function isn't available might be when your function crashes for whatever reason or when the client has spotty internet connection.

More we know about your setup, more useful we can be here. Would love to see if you can share additional info.

**Comment by jasan-s** [comment]
I am still facing this issue even with using` /myapp\.com$/` in the cors array

**Comment by OB42** [comment]
same here with V1 functions
