### ISSUE TITLE
Max instances of 0 is not clearing the limit

### ISSUE THREAD

**Issue by jbromberg** [firebase/firebase-functions#1460]
### Version info

**node:**
v16.14.2

**firebase-functions:**
4.4.1

**firebase-tools:**
12.5.2

**firebase-admin:**
11.9

### Test case
```
export const test = functions
    .runWith({
      maxInstances: 0,
    })
    .https
    .onCall((data, context) => {
      //
    });
```

### Steps to reproduce
Deploy the function above.

### Expected behavior
Max instances should be cleared and should not have a limit.

### Actual behavior
The max instances limit is set to 3000.

### Were you able to successfully deploy your functions?
Yes, no errors on deploy.

To get around this, I've had to deploy my functions with a very high max instances value. This has worked and the value shows up in the console. When setting the value to 0, the console shows 3000. According to the docs, setting it to 0 is supposed to remove the default limit of 3000.

**Comment by taeold** [comment]
Hey @jbromberg - thanks for bringing this issue up!

I've tried to set max instance to 0 in Google Cloud Functions, and I'm seeing similar behavior to one you've reported here. Let me see if there is a way for me to connect with the team internally. In the meantime, feel free to create a [Firebase Support ticket](https://firebase.google.com/support) - that way we can forward your support case to the relevant team at GCP.

**Comment by taeold** [comment]
It looks like the relevant GCF doc is here:

https://cloud.google.com/functions/docs/configuring/max-instances#setting_maximum_instances_limits

which reads:

> 2nd gen Cloud Functions have a default limit of 100 for both HTTP and event-driven functions. 1st gen Cloud Functions have a default limit of 3000 for event-driven functions, but there is no default limit for 1st gen HTTP Cloud Functions. To avoid unbounded scaling events with 1st gen HTTP Cloud Functions, we recommend setting a limit, for example, 3000. 

Reading between the lines, it looks like GCF no longer allow "unlimited" scaling by setting max instances to 0 for 2nd Gen functions.

Instead, the recommendation is to set the max instance to specific value, like 10,000, if you want a highly scalable function.

My suggestion - since your HTTP functions now support `concurrency` option, which allows up to 80 requests to be handled by a single function instance, your 2nd Gen HTTP function should scale more efficiently. This truly depends on the workload, but if you really need to have large number of max instance like a million which isn't allowed by default, I'd suggest you reach out to Google Cloud support channel to make sure you can increase your quota.
