### ISSUE TITLE
I can't retrieve the previous document. const previousData = change.before.data();

### ISSUE THREAD

**Issue by Patrick386** [firebase/firebase-functions#1470]
const previousData = change.before.data(); I can't retrieve the previous document. 
The 'previousData' log value is undefined. 
How can I get document data?

   "firebase": "^8.6.8",
    "firebase-admin": "^11.10.1",
    "firebase-functions": "^4.4.1",

Node.js v18.13.0

```
exports.onChangeMessage = functions
    .firestore.document("chatMessages/{messageId}")
    .onWrite(async (change, context) => {
        const newData = change.after.exists ? change.after.data() : null;
        // const previousData = change.before.exists ? change.before.data() : null;
        const previousData = change.before.data();

        console.log(">>> previous chat data status: ", previousData);
        console.log(">>> new chat data status: ", newData?.status);
    });
```

<img width="959" alt="스크린샷 2023-10-16 오전 10 55 56" src="https://github.com/firebase/firebase-functions/assets/49754877/9530fcf9-a453-4ee0-aa51-3ec818d2f28a">

<img width="781" alt="스크린샷 2023-10-16 오전 11 05 39" src="https://github.com/firebase/firebase-functions/assets/49754877/677890b0-4182-4bae-8474-53fcb779e1d3">

**Comment by blidd-google** [comment]
The `onWrite` trigger is invoked for all changes to a document; if you are creating a new document, then there will be no data in the `before` property.

However I would first recommend that you try out 2nd gen Firestore triggers! You can find the docs [here](https://firebase.google.com/docs/functions/firestore-events?gen=2nd)l the 2nd gen triggers have a slightly different interface.

I'm going to close this since GitHub issues are reserved for reporting bugs, but you can reach out to Firebase Support [here](https://firebase.google.com/docs/functions/firestore-events?gen=2nd) if you continue to have trouble writing Firestore functions.

**Comment by Patrick386** [comment]
> The `onWrite` trigger is invoked for all changes to a document; if you are creating a new document, then there will be no data in the `before` property.
> 
> However I would first recommend that you try out 2nd gen Firestore triggers! You can find the docs [here](https://firebase.google.com/docs/functions/firestore-events?gen=2nd); the 2nd gen triggers have a slightly different interface, but the logic is similar.
> 
> I'm going to close this since GitHub issues are reserved for reporting bugs, but you can reach out to Firebase Support [here](https://firebase.google.com/docs/functions/firestore-events?gen=2nd) if you continue to have trouble writing Firestore functions.

understand. Let's use the 2nd trigger. thank you
