### ISSUE TITLE
Auth: consumeAppCheckToken not working

### ISSUE THREAD

**Issue by jostster** [firebase/firebase-functions#1473]
### [REQUIRED] Version info

**node:** 16

**firebase-functions:** ^4.4.1

**firebase-tools:** ^9.14.0

**firebase-admin:** ^11.7.0

### [REQUIRED] Test case

See steps to reproduce below

### [REQUIRED] Steps to reproduce

1. Adding the code
```
exports.beforeSignIn = functions.runWith({
        enforceAppCheck:true,
        consumeAppCheckToken: true
    }).auth.user().beforeSignIn((user, context) => {
        console.log('User signed in');
});
```
2. In your browser open network inspector from developer console.
3. Login to your application
4. Select the `signInWithPassword` item from the network inspector and copy as cURL.
5. Edit the username / password from the curl command to another user and password and run the curl command

### [REQUIRED] Expected behavior

Error saying the app check token is invalid and login fails.

We expect the auth process to consume the app check token on a successful login.
### [REQUIRED] Actual behavior
App Check token is not consumed on login and no error is shown in console. A refresh_token and idToken are returned as a successful login.

### Were you able to successfully deploy your functions?
Yes

**Comment by taeold** [comment]
Hi @jostster - sorry for a late response.

The `enforceAppCheck` and `consumeAppCheckToken` only applies the [Callable Functions](https://firebase.google.com/docs/functions/callable?gen=2nd) and not other functions like the auth blocking function.

Because of the way the SDK is designed, the autocomplete probably led you astry into suggesting `consumeAppCheckToken` as a valid option for auth blocking function. Unfortunately, it isn't, and that's why we decided to rewrite the 2nd Gen API with a different design.

Implementing App Check token check & consumption should be easy to implement for your auth blocking function using the firebase admin sdk - see https://github.com/firebase/firebase-functions/blob/3e7a4b77967e46a067712445c499c5df005b8e31/src/common/providers/https.ts#L631 for an example.
