### ISSUE TITLE
PubSub: PubSubOptions.eventFilters not creating a filter

### ISSUE THREAD

**Issue by d7p** [firebase/firebase-functions#1475]
### Related issues

[colerogers.change-eventfilters](https://github.com/firebase/firebase-functions/pull/1070)
[dl-cf3v2-eventfitlers](https://github.com/firebase/firebase-functions/pull/1052)
[colerogers.change-eventfilters](https://github.com/firebase/firebase-functions/pull/1070)
[dl-cf3v2-cc-efs](https://github.com/firebase/firebase-tools/pull/4240)

### [REQUIRED] Version info

**node:** v18.12.1

**firebase-functions:** 4.4.1

**firebase-tools:** 12.7.0

**firebase-admin:** 11.11.0

### [REQUIRED] Test case
`import {
  onMessagePublished,
  PubSubOptions,
} from "firebase-functions/v2/pubsub";
exports.specialMessageListener = onMessagePublished(
{
  topic: "myTopic",
  region: region,
  eventFilters: [
    {
      attributes: "type",
      value: "specialMessage",
    },
  ],
} ,
  myFunctionToHandleSpecialMessages
); 
function myFunctionToHandleSpecialMessages( event: CloudEvent<MessagePublishedData<any>>
): void  {
console.log(event.data.message.attributes);
}
`

### [REQUIRED] Steps to reproduce
create a function as below:
exports.specialMessageListener = onMessagePublished(
{
  topic: "myTopic",
  region: region,
  eventFilters: [
    {
      attributes: "type",
      value: "specialMessage",
    },
  ],
} ,
  myFunctionToHandleSpecialMessages
); `

Deploy the function. check the pubsub topic subscription details.
 

### [REQUIRED] Expected behavior
when firebase is deployed the subscription filter is set and the firebase function only recives messages that match the subscription filter
![Screenshot 2023-10-24 at 14 41 14](https://github.com/firebase/firebase-functions/assets/745957/87eef765-ebe4-48e0-b9be-601243935a2b)

### [REQUIRED] Actual behavior
The filter is not set and the function is triggered on all pubsub messages sent to the topic
![Screenshot 2023-10-24 at 13 58 18](https://github.com/firebase/firebase-functions/assets/745957/16dfa373-973e-4bc7-ab74-96d55260bf71)

### Were you able to successfully deploy your functions? yes 

I don't think this is a bug so much as missing docs on how to add a filter to a pubsub subscription from firebase. 
I have tried several ways to set the eventFilter and either I get a typescript error or the functions deploy but missing the filtters (see screen shoot under actual behavior). 
In the docs the description is just says TODO (see below)
![Screenshot 2023-10-24 at 13 59 03](https://github.com/firebase/firebase-functions/assets/745957/57e59b5b-735f-4a03-bd3b-4212a99298d9)

@taeold has several merges in firebase tools and functions repos that suggest the format should be like:
`eventTrigger: {
  eventType: "pubsub_event",
  eventFilter: [
  {
    attribute: "resource",
    value: "my-storage-bucket",
  }.
  {
    attribute: "appId",
    value: "12345",
  }.
  ]
}`

this is then supported by the [extensions documentation](https://firebase.google.com/docs/extensions/publishers/functions ) that has the same structure in the yaml example however [PubSubOptions](https://github.com/firebase/firebase-functions/blob/3e7a4b77967e46a067712445c499c5df005b8e31/src/v2/providers/pubsub.ts#L154) nor [EventHandlerOptions](https://github.com/firebase/firebase-functions/blob/3e7a4b77967e46a067712445c499c5df005b8e31/src/v2/options.ts#L262) don't have `eventTrigger` as a option. I have tried using `eventFilter` in the the `PubSubOption` like:

`onMessagePublished(
{
  topic: "myTopic",
  region: region,
  eventFilters: [
    {
      attributes: "type",
      value: "specalMessage",
    },
  ],
} ,
  myFunctionToHandleSpecalMessages
); `

This deploys fine but it doesn't set the filter. I have tried several other ways to set the filter with no luck. Can you help with an example of what I have missed please. 

Thank you for the help.

**Comment by Berlioz** [comment]
The EventFilter is an implementation detail of the EventArc trigger which is backing a pubsub function. Setting the `topic` of a pubsub function causes the SDK to [generate](https://github.com/firebase/firebase-functions/blob/3e7a4b77967e46a067712445c499c5df005b8e31/src/v2/providers/pubsub.ts#L346) an `EventTrigger` containing that topic as its EventFilter; the PubSubOptions struct doesn't contain a field for eventFilter because it wouldn't do anything.

The code you saw that @taeoid wrote likely covers the EventArc integration or is test cases for it.

**Comment by d7p** [comment]
PubSubOptions extends options.EventHandlerOptions that has:  
```
eventFilters?: Record<string, string | Expression<string>>;
eventFilterPathPatterns?: Record<string, string | Expression<string>>;
```

the SDK doesn't add a filter at all (as far as i can see) it creates the subscription to the topic but ignores the filter ( see the screen shots)

**Comment by d7p** [comment]
HI @Berlioz 
you reply doesn't make sense given that the PubSubOption class extends the EventHandlerOptions and no filter is set at all when the functions are deployed. see my original question and follow up

**Comment by maylorsan** [comment]
Hi @Berlioz and team,

Thanks for the clarification earlier. I understand that the current implementation doesn’t propagate eventFilters into the underlying Pub/Sub subscription, even though PubSubOptions extends EventHandlerOptions.

That said, this is definitely a feature I’d love to see officially supported in Firebase Functions for Pub/Sub. Being able to define attribute-based filters at deployment time (e.g., only handle messages where attributes.type === "specialMessage") would be hugely beneficial in reducing cold starts, costs, and unnecessary invocations.

Currently, since the SDK ignores eventFilters when deploying onMessagePublished() handlers, I’m left with two not-so-ideal options:

- Filtering manually inside the function (which still triggers on every message)
- Or abandoning onMessagePublished and manually creating filtered subscriptions outside of Firebase (e.g. via gcloud pubsub subscriptions create with --filter and pushing to an HTTP endpoint)

Neither feels very native or ergonomic in the Firebase ecosystem.

**Comment by iq-ls** [comment]
+1
