### ISSUE TITLE
Error: Cannot find module 'firebase-functions' 

### ISSUE THREAD

**Issue by Mika83AC** [firebase/firebase-functions#148]
The issue #132 seems to be relevant again.

I'm experiencing this issue right now, but not while deploying the function to Firebase, but when it get's triggered/executed.

'firebase-functions' is present as dependency in the package.json, so this can't be the source of the issue. And as said, the deploy via "firebase deploy" also gives me no error. Just the execution.

**Comment by laurenzlong** [comment]
Hey @Mika83AC this was a production issue which should have been fixed by now. If anyone experience something similar in the future (where the error is during execution, not deployment), please open a support ticket at https://firebase.google.com/support/contact/bugs-features/ so it can be triaged properly.
