### ISSUE TITLE
Consider exporting `SecretParam` type 

### ISSUE THREAD

**Issue by vajahath** [firebase/firebase-functions#1549]
### Related issues

A PR is already open for this: https://github.com/firebase/firebase-functions/pull/1350 (Feb 2023)

So we can do:
```ts
import { SecretParam } from "firebase-functions/params";

```
### [REQUIRED] Version info

**node:**

**firebase-functions:**

**firebase-tools:**

**firebase-admin:**

**Comment by colerogers** [comment]
Hi @vajahath thanks for opening this issue & the associated PR. Historically, we don't like to export our internal types/interfaces because we can change implementation details without having to do a breaking change release. We created `defineSecret` as the public interface for customers to use. I'm curious to what issue this solves for you?

**Comment by vajahath** [comment]
I'm convinced. This can be closed.

@YannicEl do you have any comments? ([Based on your comments from the PR](https://github.com/firebase/firebase-functions/pull/1350#issuecomment-1509628034))

**Comment by gregfenton** [comment]
It is a bit strange to have a value returned by a function, but then not be able to pass that value by type to another function.

Why return a `SecretParam` if really the only thing we can do is extract its `string` value and use (or pass) that?  Why not simply have the value be passed as a `string` ?

In my case I was looking to:
```ts
const mySecretKey = defineSecret('MY_SUPER_SECRET_KEY');

export const onUpdate = onDocumentUpdated(
  {
    document: `${FIRESTORE_ACT}/{actId}`,
    secrets: [mySecretKey],
    memory: '512MiB',
    timeoutSeconds: 300,
  },
  async (event) => {
    const t8sConf = initializeMyProcessingEngine(mySecretKey);
```

but since my TS code cannot import `SecretParam`, then I cannot pass that parameter along.  I can pass `mySecretKey.value()` as a `string`.....but what's the purpose or benefit of getting the `mySecretKey` ?

I could be misunderstanding, but this feel like a "implementation detail we are hiding" while also making it clear that we are required to understand the implementation quite a bit (i.e. I need to do `mySecretKey.value()` to pass along the value.
