### ISSUE TITLE
Don't verify auth token on public endpoints

### ISSUE THREAD

**Issue by AlexJetplan** [firebase/firebase-functions#1557]
### [REQUIRED] Version info

**node:**

v18.19.0

**firebase-functions:**
4.9.0

**firebase-tools:**

13.5.2

**firebase-admin:**
12.0.0

### [REQUIRED] Test case

- Create a public endpoint
  - Any type of endpoint will do, it can literally just return hello world
  - It needs to be public

````ts
export const heartbeat = onRequest({ cors: true }, (request, response) => {
	const data  = {
		isConnected: true,
		timestamp: new Date().getTime(),
	}
	response.json({ data })
})
````

### [REQUIRED] Steps to reproduce

- Send a request to that endpoint with a valid auth token in the `Auhtorization` header
  - It should work
- Send a request to that endpoint without any token at all and no header
  - It should work
- Send a request to that endpoint with an invalid auth token in the `Authroization` header
  - It will reject the request     

### [REQUIRED] Expected behavior
Since it's a public endpoint it should always return a response, no matter if the token is provided, valid, or invalid. I have had cases in the past where the js SDK would cause the token to become invalid and users couldn't access public endpoints anymore, one of which was a heartbeat endpoint to make sure the user is still connected.

### [REQUIRED] Actual behavior
The request is rejected when you provide an auth header with an invalid token.

### Were you able to successfully deploy your functions?
Yes

**Comment by colerogers** [comment]
Hey @AlexJetplan you need to set the invoker to public to allow the function to serve public requests. You can put it directly in the options object where you specify cors (or alternatively in the global options for all funcitons):

```js
export const heartbeat = onRequest({ cors: true, invoker: "public" }, (request, response) => {
	const data  = {
		isConnected: true,
		timestamp: new Date().getTime(),
	}
	response.json({ data })
})
```

Thanks

**Comment by AlexJetplan** [comment]
> Hey @AlexJetplan you need to set the invoker to public to allow the function to serve public requests. You can put it directly in the options object where you specify cors (or alternatively in the global options for all funcitons):
> 
> ```js
> export const heartbeat = onRequest({ cors: true, invoker: "public" }, (request, response) => {
> 	const data  = {
> 		isConnected: true,
> 		timestamp: new Date().getTime(),
> 	}
> 	response.json({ data })
> })
> ```
> 
> Thanks

Hey, my apologies, I posted the wrong same code, the issue was in regards to `onCall`. In fact if you use `onRequest` as described in my post it actually works, it only doesn't work when you use `onCall`.

The issue also isn't that it isn't publicly available, the issue is that it is accessible by anybody but at the same time if you provide an invalid token it will reject the request.

I have updated the issue with the code that won't work, my apologies!

**Comment by exaby73** [comment]
Hey @AlexJetplan. How are you invoking this function? Via an HTTPS request?

**Comment by AlexJetplan** [comment]
> Hey @AlexJetplan. How are you invoking this function? Via an HTTPS request?

Hey!

In our app we are invoking it using the firebase sdk, but for you to reproduce the issue more easily you can just use a regular https client like postman or curl or whatever you want, anything will work. The important bit is that you have to send a request that has the `Authorization` header with an invalid token.

**Comment by exaby73** [comment]
Is there a use case where you need to send an invalid token to a public endpoint? I feel like this can be solved by omitting the token from the client if I am not wrong

**Comment by AlexJetplan** [comment]
> Is there a use case where you need to send an invalid token to a public endpoint? I feel like this can be solved by omitting the token from the client if I am not wrong

If you are using the firebase sdk you don't have control over the header being emitted or not. You simply just do:

````ts
functions.httpsCallable('functionName')()

````

**Comment by exaby73** [comment]
Just to understand your case better, is the SDK sending an invalid auth header?

**Comment by AlexJetplan** [comment]
> Just to understand your case better, is the SDK sending an invalid auth header?

Yes the sdk is sending an invalid auth header.

They are invalid in the sense that the auth token probably expired. So it's not the formatting that's invalid, it's the token itself.

**Comment by AlexJetplan** [comment]
bump

**Comment by CorieW** [comment]
Hi @AlexJetplan,

I've been able to reproduce this and will take a further look. Hopefully, we can get somewhere with this.

[MRE](https://github.com/invertase/cloud-team-mre/tree/firebase/firebase-functions/issue-1557/firebase/firebase-functions/issue-1557)

**Comment by cabljac** [comment]
We've been looking into this and wanted to share our analysis of the root cause and a potential fix.

The problem: In `wrapOnCallHandler`, invalid auth tokens are unconditionally rejected, while missing tokens pass through silently. This means a public endpoint works fine with no Authorization header, but breaks if a client sends a stale or expired toke. The Firebase SDK can do this automatically.

The relevant code path:

```typescript
const tokenStatus = await checkTokens(req, context, options);
if (tokenStatus.auth === "INVALID") {
  throw new HttpsError("unauthenticated", "Unauthenticated"); // hard throw, no opt-out
}
```
Compare this with AppCheck, which has a gate:

```typescript
if (tokenStatus.app === "INVALID") {
  if (options.enforceAppCheck) {
    throw new HttpsError("unauthenticated", "Unauthenticated");
  } else {
    logger.warn("Allowing request with invalid AppCheck token because enforcement is disabled");
  }
}
```
Auth has no equivalent mechanism.

Also to note, `invoker: "public"` can't solve this: invoker is a deployment-time IAM setting. it configures Cloud Run access control via the Firebase CLI and isn't available to the SDK at runtime.

The internal CallableOptions interface (which checkTokens and wrapOnCallHandler receive) contains enforceAppCheck, consumeAppCheckToken, authPolicy, cors, and heartbeatSeconds, but no invoker and no auth enforcement toggle.

Additional issue: The existing authPolicy callback on CallableOptions should be the right place for developers to make their own auth decisions... but the hard throw on `"INVALID"` happens before authPolicy runs, so it never gets the chance to execute.

**Comment by cabljac** [comment]
I see two options:

- add enforceAuth as an opt-in option to CallableOptions which defaults to `true` so it's non-breaking 

- just make it return "MISSING" in this path (simpler but breaking)

The first option is probably the best and safest

**Comment by cabljac** [comment]
Hey @AlexJetplan  just want to clarify the use case here:

Are you using Firebase Auth and just running into stale/expired tokens on public endpoints, or are you actually using a different identity provider (Auth0, custom JWTs, etc) and the Firebase token validation is getting in the way?

**Comment by ghost** [comment]
> Hey [@AlexJetplan](https://github.com/AlexJetplan) just want to clarify the use case here:
> 
> Are you using Firebase Auth and just running into stale/expired tokens on public endpoints, or are you actually using a different identity provider (Auth0, custom JWTs, etc) and the Firebase token validation is getting in the way?

We are moving away from firebase right now because of other major problems with the infra. But to answer your question, we were using the official firebase sdk in the frontend. I don't know how or why, but the sdk would cause stale tokens which would be used to request a public endpoint before the token was refreshed. That caused the public endpoint to fail.

In our case specifically, we had a "hearbeat" endpoint which was just a simple endpoint with basically no return value, which only purpose was to check if the user is online or not. The user requests the endpoint (using the official sdk), if a response is returned, we know the user is online.

If you don't get a response, or you get an error, we will show a "disconnected" screen.

This is functionality that works for both logged in users and logged out users.

So people would often get "disconnected" screens because their token went stale and the **public** endpoint rejected their request.

To be honest, this isn't really about our use case, as I said we are leaving the firebase eco system, and as I described in the issue, we have found a workable workaround.

The intention behind this issue was to let you guys know that there is an inconsistency in how tokens are handled depending on which type of endpoint you chose. And that rejecting an invalid access token on a public endpoint is bad design in my opinion.

If you don't think this is a conceptual problem then you can also close the issue. I am mentioning this to avoid you guys keeping the issue open because you think we are waiting for a solution to integrate into our app.
