### ISSUE TITLE
[logger]: express deprecated req.host: Use req.hostname instead

### ISSUE THREAD

**Issue by jdcoldsmith** [firebase/firebase-functions#1569]
### [REQUIRED] Version info

4.9.0 (I realize that this isn't the latest version but I have compared the code and couldn't find anything related to `logger`)

**node:**

20

**firebase-functions:**

Hello, I recently experienced this error in a 2nd gen Node.js 20 firebase function and I wanted to pass it along to you fine folks.
![image](https://github.com/firebase/firebase-functions/assets/65235172/14f7b6f2-f1c5-4865-9e66-36d144bae236)
This seems to be an issue with the `logger` package.

**Comment by exaby73** [comment]
Hey @jdcoldsmith. Could you give me a code sample that causes this log?

**Comment by jdcoldsmith** [comment]
It seems to happen for me whenever I call `log` within an `onRequest` firebase function. This is how I import `log`: `const { log } = require('firebase-functions/logger');`

**Comment by taeold** [comment]
Hi @jdcoldsmith. We reviewed our source code and don't see any direct reference to the `req.host` object.

I'm wondering what object you are passing to the logger module. The logger module will iterate through all keys in an object that is passed while serializing the object, and maybe the `req.host` is being used within that code.

**Comment by jdcoldsmith** [comment]
Ahh ok I think I see what could be happening. Whenever I get an error in my function I am passing the entire express request to the `log` function of logger (e.g. `log('Error', { request })`). Is it possible that logger throwing this warning from that?

**Comment by exaby73** [comment]
Hey @jdcoldsmith. Yeah this is entirely possible since the logger iterates over the entire object to format it correctly before actually logging it. I'd recommend you log only properties you're interested in, like the `hostname`, any query params, etc. instead of logging the entire request object which may be logging a lot of unnecessary information polluting your logs.

But since this is not an issue with the logger itself, I feel safe to close this issue. Thank you!

**Comment by jdcoldsmith** [comment]
Ok that makes sense! Thank you!

**Comment by nilsreichardt** [comment]
I fixed it by running `npm update`.
