### ISSUE TITLE
v5.1.0 requires firebaseextensions.googleapis.com when Extensions are unused in a project

### ISSUE THREAD

**Issue by bkendall** [firebase/firebase-functions#1596]
### [REQUIRED] Version info

**node:**

`v20.16.0`

**firebase-functions:** `v5.1.0`

**firebase-tools:** `v13.15.2`

**firebase-admin:** `v12.1.1`

### [REQUIRED] Steps to reproduce

After updating `firebase-functions` from 5.0.1 to 5.1.0, deploying no longer works.

### [REQUIRED] Expected behavior

Successful deploy.

### [REQUIRED] Actual behavior

I now get an error that the Extensions API isn't enabled, even though it's unused by the project.

```
[2024-08-19T22:29:41.411Z] >>> [apiv2][query] GET https://firebaseextensions.googleapis.com/v1beta/projects/XXXXX/instances pageSize=100&pageToken=
[2024-08-19T22:29:41.624Z] <<< [apiv2][status] GET https://firebaseextensions.googleapis.com/v1beta/projects/XXXXX/instances 403
[2024-08-19T22:29:41.624Z] <<< [apiv2][body] GET https://firebaseextensions.googleapis.com/v1beta/projects/XXXXX/instances {"error":{"code":403,"message":"Firebase Extensions API has not been used in project XXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firebaseextensions.googleapis.com/overview?project=XXXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Google developers console API activation","url":"https://console.developers.google.com/apis/api/firebaseextensions.googleapis.com/overview?project=XXXXX"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"SERVICE_DISABLED","domain":"googleapis.com","metadata":{"service":"firebaseextensions.googleapis.com","consumer":"projects/XXXXX"}}]}}
```

### Were you able to successfully deploy your functions?

No.

**Comment by bkendall** [comment]
When I'm deploying locally, I see that issue above.

When I deploy via GH Action, I actually get a different API that isn't enabled (I assume because it's deploying with a workload identity instead):

```
Error: HTTP Error: 403, Cloud Billing API has not been used in project XXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudbilling.googleapis.com/overview?project=XXXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

**Comment by bkendall** [comment]
Thanks for [the fix](https://github.com/firebase/firebase-tools/releases/tag/v13.15.3)!

**Comment by ifielker** [comment]
You're welcome :)

**Comment by CarltonK** [comment]
Updating firebase-tools to the latest version worked for me
13.15.3

**Comment by steveoh** [comment]
I'm getting the firebaseextensions.googleapis.com and cloudbilling.googleapis.com errors in my ci with the following dependencies. From some other issues it sounds like this is normal and expected now?

├── firebase-functions@6.0.1
├── firebase-tools@13.20.2

**Comment by Schmale97** [comment]
This looks to have been re-introduced, currently getting the error for 
firebase-functions@6.1.0
firebase-tools@13.24.2

**Comment by ixjamesyoo** [comment]
> This looks to have been re-introduced, currently getting the error for firebase-functions@6.1.0 firebase-tools@13.24.2

Can confirm the issue was re-introduced on my end as well.

firebase-functions@6.1.0 firebase-tools@13.25.0

Reverted firebase-functions@5.0.1, and deployment worked fine again

**Comment by ifielker** [comment]
The firebaseextensions.instance.list permission is now required for any firebase deploy that includes functions. This is expected. It is because we have launched new features that allow you to define extension instances in your functions codebase and deploy them that way. See [https://firebase.google.com/docs/extensions/install-extensions?interface=sdk)](https://firebase.google.com/docs/extensions/install-extensions?interface=sdk) for details.

This means that when we deploy functions we will always be checking if you have extension instances in your project that were defined using an autogenerated SDK in a deploying codebase. So we need to list the current extension instances in your project to determine if there is anything to potentially delete or configure or update.

Consider enabling the Firebase Extensions Viewer permission which includes the ability to list extension instances.

**Comment by ixjamesyoo** [comment]
@ifielker  Thanks for the quick response. 

This was helpful context -- I initially understood the function deployment failures as a regression in the `firebase-functions` dependency because our codebase is not leveraging extensions, and so the error messages during deployment were not easily understood. Even though I intuited the potential solution of adding the stated Firebase Extensions Viewer role to our deployment service account, the reasons behind doing so were unclear and I was hesitant to do so.

Are there plans to mitigate these errors, e.g. by skipping over projects where the Extensions api is not enabled?

Otherwise a more detailed error message during deployment explaining the above could help out. Docs don't seem to be up to date in this regard

**Comment by ArjunIsCool** [comment]
Is there some way to circumvent this error without having to grant extension permissions? Sorry for necro.

**Comment by bdlgq-mike** [comment]
I am getting this error today, no changes to my setup. it was working, then all of a sudden i was getting the

Error: Request to https://firebaseextensions.googleapis.com/v1beta/projects/XXXXXXX/instances?pageSize=100&pageToken= had HTTP Error: 403, The caller does not have permission

**Comment by samueladesoga** [comment]
Getting same error suddenly. in last 30mins

**Comment by Andrew-Hopkins-Akcelo** [comment]
@ifielker This error seems to have been re-introduced.

Started getting this within the last hour.
( with only 1 line of unrelated code change to my pre-existing project )

**Comment by qlereboursFR** [comment]
Same for me, and landed on this topic

**Comment by Ihernandezpi** [comment]
Same problem 

<img width="1340" height="71" alt="Image" src="https://github.com/user-attachments/assets/b55d3519-111d-4ce8-9126-dae9e57b01e9" />

**Comment by sds100** [comment]
Me too!

**Comment by EIleven** [comment]
Same here, seems to be a general problem

**Comment by m-rios** [comment]
mee too 🙄

**Comment by EIleven** [comment]
They apparently posted a faulty update to the CLI in the last few hours that politely checked the Extensions API worldwide, blocking deployments globally with this false "Error 403".

**Comment by dnathe4th** [comment]
Thumbs up if claude sent you here

**Comment by EIleven** [comment]
I literally had to search GitHub/Stack Overflow, like the old-timers did.

**Comment by stefon-rentor** [comment]
Can confirm this issue is happening as well. Been deploying for two weeks. No changes. Randomly getting this 403 despite being an Owner with every possible thing done. Signing out. Signing back in. Disabling and Reenabling Extenstions API, etc.

It seems the only solution may be to manually patch the buggy CLI to allow it to skip this useless check it's doing. Most of us have no use for Extenstions at all yet it still forces this check.

`i  extensions: ensuring required API firebaseextensions.googleapis.com is enabled...`

Which then blocks us from deploying due to Googles bug despite us not even using Extenstions due to this well known bug so we shouldn't be forced to suffer those bugs...

`[2026-02-26T23:44:23.379Z] Error Context: {
  "body": {
    "error": {
      "code": 403,
      "message": "The caller does not have permission",
      "status": "PERMISSION_DENIED"
    }
  },
  "response": {
    "statusCode": 403
  }
}`

**EDIT: I spent two hours troubleshooting. The fix is actually easy and takes 5min to enable a feature Google should have done before since Extenstions check is useless for us without them. All you have to do is manually patch the buggy CLI to allow you to skip the useless extenstions check.**


### Fix for Firebase CLI Extensions API 403 Error
**Issue**: Firebase CLI v14+ requires Extensions API permissions during deployment, even if you're not using Firebase Extensions. This causes a 403 error whenever Google decides to introduce a bug.

**Workaround**: Patch the Firebase CLI to skip the Extensions API check.

**Step 1: Find your Firebase CLI installation**
`npm root -g`
This will output something like: `/home/username/.nvm/versions/node/v20.9.0/lib/node_modules`

**Step 2: Edit the prepare.js file**
Open this file in your editor:
`<npm-root-from-step-1>/firebase-tools/lib/deploy/extensions/prepare.js`

**Step 3: Apply the patches**

**Patch 1 (around line 125-129):**

```
// BEFORE:
await (0, extensionsHelper_1.ensureExtensionsApiEnabled)(options);
await (0, requirePermissions_1.requirePermissions)(options, ["firebaseextensions.instances.list"]);
let haveExtensions = await planner.haveDynamic(projectId);

// AFTER:
// PATCHED: Skip Extensions API check to avoid 403 error
// await (0, extensionsHelper_1.ensureExtensionsApiEnabled)(options);
// await (0, requirePermissions_1.requirePermissions)(options, ["firebaseextensions.instances.list"]);
let haveExtensions = []; //await planner.haveDynamic(projectId);
```

**Patch 2 (around line 146-148):**

```
// BEFORE:
await (0, extensionsHelper_1.ensureExtensionsApiEnabled)(options);
await (0, requirePermissions_1.requirePermissions)(options, ["firebaseextensions.instances.list"]);

// AFTER:
// PATCHED: Skip Extensions API check to avoid 403 error
// await (0, extensionsHelper_1.ensureExtensionsApiEnabled)(options);
// await (0, requirePermissions_1.requirePermissions)(options, ["firebaseextensions.instances.list"]);
```

**Patch 3 (around line 155-156):**

```
// BEFORE:
const haveExtensions = await planner.have(projectId);

// AFTER:
const haveExtensions = []; // PATCHED: Skip fetching existing extensions to avoid 403
```

**Comment by dnathe4th** [comment]
Also came back to suggest a work around. After some exploration with Claude we just early returned `prepare` and `prepareDynamicExtensions` directly and am able to deploy function. Claude says:

>In node_modules/firebase-tools/lib/deploy/extensions/prepare.js, two functions were patched with early returns:
>
>  1. **prepare** (line 140) — runs when extensions is in the deploy target list. Checks extensions API is enabled, verifies firebaseextensions.instances.list permission, then diffs what extensions you want vs have.
>  2. **prepareDynamicExtensions** (line 120) — called from the functions deploy path if any function build references extensions. Does the same API/permission checks before processing dynamic extension configs.
>
>  Both hit the firebaseextensions.googleapis.com/v1beta/projects/{id}/instances endpoint which is currently returning 403 across many projects due to a Google-side issue (https://github.com/firebase/firebase-functions/issues/1596). The patch is safe since you don't use extensions — these functions do nothing useful for your project. Note  that npm install -g firebase-tools will overwrite the patch.

**Comment by gunnarmein-ts** [comment]
I have the same issue. I don't see how the workaround will work for our GitHub-based deployment.

**Comment by gunnarmein-ts** [comment]
@ifielker (the only name I see here) can we get this reopened?

**Comment by Andrew-Hopkins-Akcelo** [comment]
@stefon-rentor 's workaround succeeded for me, allowing me to manually deploy the functions.

Note: You will want to apply this update to either your global firebase-tools install, or your applications firebase-tools module itself


Here's a terminal command you can run to apply stefon's workaround

You will want to run this from either
-  `/home/<username>/.nvm/versions/node/<INSERT NODE VERSION>/lib/node_modules/firebase-tools`  ( Global Install )
- `webapp-root/node_modules/firebase-tools/` ( Local Application Install )



```
# Apply workaround using sed
sed -i \
  -e 's|await (0, extensionsHelper_1.ensureExtensionsApiEnabled)(options);|//await (0, extensionsHelper_1.ensureExtensionsApiEnabled)(options);|g' \
  -e 's|await (0, requirePermissions_1.requirePermissions)(options, \["firebaseextensions.instances.list"\]);|//await (0, requirePermissions_1.requirePermissions)(options, ["firebaseextensions.instances.list"]);|g' \
  -e 's|let haveExtensions = await planner.haveDynamic(projectId);|let haveExtensions = []|g' \
  -e 's|const haveExtensions = await planner.have(projectId);|const haveExtensions = []|g' \
  lib/deploy/extensions/prepare.js

```


Note: 
- I am just a random dev sharing a workaround to this bug.
- I am NOT an official Firebase developer
- This should be used as a temporary fix until the Firebase team actually implement a proper fix.
- This code is not malicious, but with that being said, please use at your own risk.
  -  I take no responsibility if this code destroys your pc, grows legs, gains sentience, or attempts to destroy humanity.

**Comment by aderderian** [comment]
Still happening for me right now

**Comment by risalfajar** [comment]
Seems like a regression, please reopen @bkendall

**Comment by RyanCarrier** [comment]
Here is the temporary patch as a CI step


```
    - name: Patch firebase-tools extensions check (temp workaround)
      shell: bash
      run: |
        # Workaround for https://github.com/firebase/firebase-functions/issues/1596
        # Firebase CLI 403 on Extensions API - skip check since we don't use extensions
        PREPARE_JS="$(npm root -g)/firebase-tools/lib/deploy/extensions/prepare.js"
        SED="sed"; [[ "$OSTYPE" == darwin* ]] && SED="gsed"
        $SED -i \
          -e 's|await (0, extensionsHelper_1.ensureExtensionsApiEnabled)(options);|//await (0, extensionsHelper_1.ensureExtensionsApiEnabled)(options);|g' \
          -e 's|await (0, requirePermissions_1.requirePermissions)(options, \["firebaseextensions.instances.list"\]);|//await (0, requirePermissions_1.requirePermissions)(options, ["firebaseextensions.instances.list"]);|g' \
          -e 's|let haveExtensions = await planner.haveDynamic(projectId);|let haveExtensions = [];|g' \
          -e 's|const haveExtensions = await planner.have(projectId);|const haveExtensions = [];|g' \
          "$PREPARE_JS"
```

**Comment by ArjunIsCool** [comment]
I'm a little surprised this issue that existed for so long is only
revisited now. Or did it become more worse?

**Comment by qlereboursFR** [comment]
According to [this comment](https://github.com/firebase/firebase-tools/issues/9987#issuecomment-3972121520), this is fixed. It's working for me now
