### ISSUE TITLE
Firebase-admin peer dependency not up to date

### ISSUE THREAD

**Issue by lpellegr** [firebase/firebase-functions#163]
Why is the `firebase-admin` peer dependency required by `firebase-functions` always far away from the latest release? I am not here to complain. My wish is to understand the situation. For instance, `firebase-functions` 0.8.0 needs `firebase-admin` 5.6.0 but the latest version is 5.8.0. This last version including interesting changes in my case.

**Comment by laurenzlong** [comment]
Thanks for your question! We try to keep the dependency as up to date as possible, but some times we do not do the update right away, since code changes are some times involved and we extensively test  to make sure that the new firebase-admin does not break firebase-functions in any way. You are right that we have been slow to update lately, and we need to do a better job. v0.8.1 firebase-functions now has the latest firebase-admin, so you can start using it!
