### ISSUE TITLE
Google Cloud Functions Changes

### ISSUE THREAD

**Issue by 00hello** [firebase/firebase-functions#187]
I received this email from Google yesterday. And I'm wondering if there'll be any changes to this repo to account for this?

> Hello Cloud Functions Developer,
> 
> We wanted to make you aware of a number of changes coming to Cloud Functions triggered by either Google Cloud Storage or Google Cloud Pub/Sub events. Specifically, we are (1) introducing a set of more powerful, finer-grained trigger types for Cloud Storage and (2) changing the format for Cloud Storage and Cloud Pub/Sub events.
> 
> ### New more powerful storage triggers
> ... introduced finer grained storage triggers that allow developers to invoke functions on only a subset of Cloud Storage change events as opposed to responding to all changes on a bucket. For example, you can now write a Cloud Function that only executes when a file is created or one that only executes when a file is deleted....
> 
> ## Changes to Cloud Storage and Pub/Sub events
> ### What is changing?
> ### Google Cloud Storage triggers 
> Google Cloud storage triggers will use the new finer grained event types mentioned above. As a result, the format of the events will change, and the behavior of the 'gcloud beta functions deploy --trigger-bucket' command will be changing shortly to use the new triggers. After February 28, 2018, deploying a new function with this command will no longer cause it to receive Cloud Storage object change notifications. Instead, it will cause your function to only trigger on OBJECT_FINALIZE events--when a new file is created.

....

> ### What happens to my running functions?
> Your running functions will not be affected by either of these changes at this time. They will continue to receive events as usual and with the current schema. These older, legacy event types, however, are no longer being actively supported and will remain in beta indefinitely.

> ### What if I want to update one of my functions that is using a legacy event type?
> After February 28, 2018, attempting to update a function that is using a legacy event type via the --trigger-bucket or --trigger-topic flag in gcloud will not succeed. If you want to update one of your existing functions, we have preserved the legacy Cloud Storage and legacy Pub/Sub events. These will allow you to continue to maintain your code even after the gcloud SDK behavior is changed to take advantage of the new Cloud Storage and Cloud Pub/Sub events.

**Comment by laurenzlong** [comment]
Hi @00hello These changes will be a part of firebase-functions v1.0.0, we will have migration documentation ready for that time. So the section titled "What if I want to update one of my functions that is using a legacy event type?" does not apply to you right now.

**Comment by 00hello** [comment]
@laurenzlong Thanks for clearing that up.

**Comment by dreadnough** [comment]
Have you any updates on this issue?

**Comment by laurenzlong** [comment]
New storage types are now in firebase-functions v1.0.0, see https://firebase.google.com/docs/functions/beta-v1-diff

**Comment by celsowhite** [comment]
Hi @laurenzlong I am just now upgrading to v1.0.0 and received an error message on my pubsub trigger.

**Error**

`Function storageCleanup was deployed using a legacy trigger type and cannot be updated with the new SDK. To proceed with this deployment, you must first delete the function by visiting the Cloud Console at: ...`

I didn't see anything in the migration guide about updating pubsub triggers so did not expect the error. I also find the 'you must first delete the function' statement to be a bit confusing. I first thought that it meant delete and rewrite in a new syntax but seems to be just delete via google cloud and redeploy.

**Migration Guide Addition**

I think it's worth mentioning/clarifying this in the [migration guide](https://firebase.google.com/docs/functions/beta-v1-diff). Although it's not a code change, it is another part of the migration process. I think it would give users more confidence in deleting their function if they read about why in the guide.

Let me know if I should post this in the support section of the site instead of here.

Thanks!

**Comment by laurenzlong** [comment]
@celsowhite Great suggestion! I'll work with our tech writers to get it in.

**Comment by laurenzlong** [comment]
@celsowhite We've added a section to our docs that explain this in more details, and the CLI message now links to it: https://firebase.google.com/docs/functions/manage-functions#modify-trigger

**Comment by celsowhite** [comment]
@laurenzlong that's great. Thanks!
