### ISSUE TITLE
firebase.apiKey missing from firebase.config()

### ISSUE THREAD

**Issue by moneal** [firebase/firebase-functions#196]
This morning I made a small change to a function and other unreleased functions started failing. It appears that the apiKey is no longer a property of the default config and this killed our application. 

What is the proper way to get the default apiKey to communication to other google services like Maps and UrlShortner?

**Comment by laurenzlong** [comment]
Hi @moneal, apiKey was an undocumented field, and we removed it. Sorry that this caused issues for your application! You can store API keys needed for your application using the 'firebase functions:config:set' command. See https://firebase.google.com/docs/functions/config-env for details.

**Comment by moneal** [comment]
Thank you letting me know what happened. We have updated accordingly.

**Comment by TheFastCat** [comment]
This also affected me - spent time tracking it down. One question is that other (non-dev) environments have this key as expected - why was it removed from one but not the others?

**Comment by laurenzlong** [comment]
It depends on the when the function was deployed, if it was deployed with firebase-tools v3.17.5 or later, then it won't have the key.

**Comment by TheFastCat** [comment]
An unexpected, breaking change on a minor version update to firebase-tools.
simply re-adding this removed key/value via cli config to "firebase" is not so straightforward since :

- the key name was previously camelCased, but we aren't allowed camel casing via CLI custom config
- 'firebase' is a reserved word, so sticking it back where it was won't work -- this leaves a firebase config variable for the apiKey unable to reside within the firebase config object - not ideal

![image](https://user-images.githubusercontent.com/4805874/37625615-9c56df1e-2b9a-11e8-9f94-e5b3e54c0cf3.png)

 since the intent seems to be (from [here](https://firebase.google.com/docs/functions/config-env)) : 'functions.config().firebase is auto-populated with configuration needed to initialize the firebase-admin SDK.'

existing code ~ 

`firebase.initializeApp(functions.config().firebase);`

after this change ~

(cli) firebase functions:config:set fire.apikey="api key here"

`firebase.initializeApp(functions.config().firebase,  apiKey: functions.config().firebase.apikey)`

is there a more elegant workaround that can be implemented in the future release? such making "firebase" no longer a reserved word? Also what is the best way for me to avoid unexpected breaking changes in future minor updates to the firebase CLI?

thank you

**Comment by laurenzlong** [comment]
Thanks for the feedback. It was definitely our mistake to not do this with more communication. Even though apiKey was an undocumented field, it is now clear that many of you were using it. 

However, please note that it is not required for initialization of firebase-admin. (See [doc](https://firebase.google.com/docs/reference/admin/node/admin.app.AppOptions)) So `firebase.initializeApp(functions.config().firebase)` will still work.

**Comment by TheFastCat** [comment]
ok thank you Lauren! No big deal and I appreciate your help.

**Comment by Tyris** [comment]
Hi @laurenzlong we use `firebase.auth().verifyPasswordResetCode` inside some of our http functions; so we can't use `firebase-admin` for this, we need to use `firebase` which **does** require the apiKey (therefor requiring a solution like the one provided by @TheFastCat ).

Are we not expected to use the likes of `verifyPasswordResetCode` in server code?

**Comment by laurenzlong** [comment]
@Tyris If you have a use case for verifyPasswordResetCode server-side, then that's a great feature request for https://github.com/firebase/firebase-admin-node.

**Comment by laurentpayot** [comment]
@juddflamm is this helpful to you? https://firebase.googleblog.com/2017/04/easier-configuration-for-firebase-on-web.html
