### ISSUE TITLE
Error: Error parsing triggers: Cannot find module 'actions-on-google'

### ISSUE THREAD

**Issue by Flypex** [firebase/firebase-functions#235]
i  deploying functions
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error parsing triggers: Cannot find module 'actions-on-google'
Try running "npm install" in your functions directory before deploying.

I don't know how to solve the problem. I have run npm-install in the functions directory, but have had no luck in getting this to work.  How can I fix the problem?

**Comment by mbleigh** [comment]
Make sure that `actions-on-google` is listed as a dependency in your `package.json` and then run `npm install` again.

**Comment by HarshHC** [comment]
@mbleigh  I am getting the same problem and I do have actions-on-google in my package.json.
But when i run npm install i get this:
`npm WARN saveError ENOENT: no such file or directory, open 'C:\users\HarshC\codelabs-nodejs\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\users\HarshC\codelabs-nodejs\package.json'
npm WARN codelabs-nodejs No description
npm WARN codelabs-nodejs No repository field.
npm WARN codelabs-nodejs No README data
npm WARN codelabs-nodejs No license field.

up to date in 17.903s
[!] 21 vulnerabilities found [9838 packages audited]
    Severity: 2 Low | 18 Moderate | 1 High
    Run `npm audit` for more detail`

and after running firebase deploy it says cannot find module message again.
Also when I do firebase --version I get the response 3.18.4  however in the codelab it is mentioned we should have it at least 3.5 . but when I checked the repo in github the latest version is 3.18.4.

Please help I do not know what to do

**Comment by thechenky** [comment]
Thank you for your feedback @gerhardcit! Unfortunately we cannot do better validation here because it's dependent on the user's code, so any issues in the global scope would show up as an error (we basically just wrap whatever npm throws).

Make sure that you compile the code if it's Typescript. I have a feeling there might be a problem with your pre-deploy hook not doing the compilation step. Can you check that you've set that up properly (use https://firebase.google.com/docs/functions/typescript as reference). If you still have issues and fixing pre-deploy hook did not work, please open another issue.

As far as suggestions on node/npm versions, we generally recommend you use a similar version you're deploying your functions in (6.14.0 for node6 https://cloud.google.com/functions/docs/concepts/nodejs-6-runtime or 8.11.1 for node8 https://cloud.google.com/functions/docs/concepts/nodejs-8-runtime).

**Comment by thechenky** [comment]
@Flypex as others pointed out, make sure to have the dependency declared in your package.json file inside your functions directory, then run `npm install .` from the same directory. I'm going to close this out now. Please file another issue if you feel you're still getting errors. Thanks everyone.
