### ISSUE TITLE
Custom configuration variable not available when running locally

### ISSUE THREAD

**Issue by ashleygeorgeclarke** [firebase/firebase-functions#294]
I have set my variable with `firebase functions:config:set stripe.key="xxxxxxx"`

`firebase functions:config:get > .runtimeconfig.json` exports config correctly to the functions folder.

```
{
  "stripe": {
    "key": "xxxxxxxxx"
  }
}
```
However using functions.config().stripe.key returns the error when running firebase serve:

TypeError: Cannot read property 'key' of undefined
    at Object.<anonymous> (C:\Users\ash\Documents\GitHub\danceform\functions\index.js:14:38)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\Users\ash\AppData\Roaming\nvm\v6.11.5\node_modules\firebase-tools\lib\triggerParser.js:21:11
    at Object.<anonymous> (C:\Users\ash\AppData\Roaming\nvm\v6.11.5\node_modules\firebase-tools\lib\triggerParser.js:75:3)

### Version info
Windows 10

firebase-admin: ^5.13.1,
firebase-functions: ^2.0.2,
firebase-tools: 4.0.0
nodejs: 6.11.5

### Test case

firebase deploy works no problem.

**Comment by dauledk** [comment]
It would be awesome if firebase could fix this.

To solve this problem right now, I use a pattern where I first check if `firebase.config()` is present. If it is, I extract the value. Otherwise I read the value from the `.runtimeconfig.json` file.

**Comment by laurenzlong** [comment]
Hi, this is expected behavior, you need to run the following command first in the functions folder:
```
firebase functions:config:get > .runtimeconfig.json
```

Local functions will automatically populate `functions.config()` from `.runtimeconfig.json`, @dauledk your workaround is not necessary as long as you ensure that the file is in the functions folder and in proper JSON format. 

Please see https://firebase.google.com/docs/functions/local-emulator

**Comment by ashleygeorgeclarke** [comment]
Issue updated as above

**Comment by ashleygeorgeclarke** [comment]
Resolved by using CMD instead of powershell to do functions:config:get >.runtimeconfig.json

**Comment by dauledk** [comment]
@laurenzlong is it not possible to add this internally in the `firebase serve` command, so you don't need to run `firebase functions:config:get > .runtimeconfig.json`?

In my humble opinion, the most significant challenge for the development experience of firebase functions is the "difference" between running functions locally and deployed. This specific issue seems relatively easy to improve, or am I missing something?

**Comment by dauledk** [comment]
@mbleigh That is indeed a very good argument. Maybe the ideal middle ground would be a function exposed by firebase-functions, with this implementation:

```typescript
getConfigVariable(path: string): string {
   // Try to get the config variable, based on the path
   // much like how lodash get() method works.

  // If the value is found, return the value and done.
  
   // If the value is not found:
   // If .runtimeconfig.json is not present, inform the user about how to access the runtimeconfig, 
   // and the dangers explained in your last comment. If its not present, simply throw an error like 
   // "not found".
}
```

Do you like that idea?

**Comment by ashleygeorgeclarke** [comment]
These replies are off-topic from the original question

**Comment by laurenzlong** [comment]
@ashleygeorgeclarke Sorry I read your original issue too quickly and didn't catch the fact that you already ran `firebase functions:config:get > .runtimeconfig.json`. You're right  the issue is with using PowerShell, this [helpful comment](https://github.com/firebase/firebase-tools/issues/711#issuecomment-392451237) from @gavanitrate indicates that the following should work in PowerShell:
`functions:config:get | ac .runtimeconfig.json`

I'll get this added to our documentation as well.
