### ISSUE TITLE
Support failurePolicy - retry

### ISSUE THREAD

**Issue by hobochild** [firebase/firebase-functions#297]
Currently, you can't pass failure policy to firebasefunctions which means you cant deploy retryable functions with `firebase-tools`. 

Not sure I'll have time to submit a PR but my two-cents on the API would be. 

 ```
exports.webhookAsia = functions
    .region('asia-northeast1')
    .failurePolicy({ retry: true }) // set retry on failure to true
    .user.onCreate((req, res) => {
            res.send("Hello");
    });
```

NOTE the gcloud functions api expects the failure policy to be formed - assume this is to future proof retry options.
```
{ failurePolicy: { retry: {}}}
```

**Comment by hobochild** [comment]
Alternatively, you could and a cli flag to the firebase-tools which patches the eventTrigger before posting it. 

like 
```
firebase deploy ----retry
```

**Comment by laurenzlong** [comment]
Thanks for filing! We've discussed this a lot internally and ultimately decided to not expose retry policies via the SDK for now, since the current retry policy retries your function repeatedly for days, which can lead to unexpectedly large bills if the error is due to a programming error. If you know what you are doing, and are ok with the consequences of enabling retries you can do so through the Google Cloud Console (console.cloud.google.com). The Google Cloud Functions team is also working on more customizable retry policies, and when that is launched, we will expose the options through the firebase-functions SDK.

**Comment by 0x80** [comment]
@laurenzlong Any update on the "more customizable retry policies"?  It looks we can still only enable retries via cloud function runtimeOptions), without specifying how many / for how long, so using this setting is still quite risky.
