### ISSUE TITLE
Support for dartlang?

### ISSUE THREAD

**Issue by dooboolab** [firebase/firebase-functions#303]
Hi! Firebase team. Thank you for your awesome contributions to open source.

Today, I am really fan of dart and flutter.
I am wondering if your team has any plan for supporting dart language.

I want to make all of my services using firebase with the dart language.
I wish that it could be possible someday.

**Comment by thechenky** [comment]
Hi @dooboolab thank you for the suggestion and the kind words! I have made sure to document your feature request internally. Closing this out.

**Comment by AirborneEagle** [comment]
@laurenzlong 
Do you have any updates on the thing that you were working on to make this possible?
After 1.5 years, I would assume that either some good progress has been made, or it has been ditched all together?

For me, it would decrease our development time by a HUGE margin.

**Comment by ludwiktrammer** [comment]
I wouldn't hold my breath - they closed and locked the other issue (#383) preventing people from even being able to vote for the issue. Meanwhile Amazon announced [Dart support in AWS Lambda](https://aws.amazon.com/blogs/opensource/introducing-a-dart-runtime-for-aws-lambda/).

**Comment by mbleigh** [comment]
GitHub issues are not the best place to add feature requests because it's not how they get tracked internally. If you want to see a feature, [filing a feature request](https://firebase.google.com/support/troubleshooter/report/features) is the best way to get the right eyes on it.

I can tell you that we do not currently have plans to support Dart in Cloud Functions for Firebase. In the future we'd like to support additional languages and runtimes in a more general sense, but I wouldn't expect changes to this in the near future.

**Comment by luca-venir** [comment]
Hi, I've seen some interest on this thread and on the other one (#383), so I'd thought to search the web a little for answers to this topic and I found out something interesting, at least to me.

Dart is a relatively "new" language when it comes to back-end, isn't it? [This 2019 article](https://medium.com/flutter-community/web-server-frameworks-for-dart-197a073299eb) describes server-side Dart and it has been recently updated to inform its readers that the two most ""popular"" (if that can be said) dart back-end frameworks have been discontinued (note how it advises to just use the `shelf` package since it's maintained by the Dart team). [By looking at search trends](https://trends.google.com/trends/explore?date=today%205-y&q=dart%20backend), server-side Dart solutions seem dead, as this topic is losing interest since the last year.

I think this is a broader problem than just Firebase's. This is just my humble opinion of course, but I'm guessing that Google should give more energies into Dart's back end potential if we want it to be reliable on production-side. This makes sense to me, since I'd expect people not to maintain Dart back-end solutions, or expand them, as long as Google isn't sponsoring this as much as they're doing it with Flutter.

To me and for many developers, having Firebase Functions support (and having a full SDK in general) would be actually a game changer. IMO, it just makes sense to push this request sooner or later, since just like Node JS, Dart is very close to Front End Developers, and it's very popular nowadays. Not to mention the classic business advantages such as costs cuts, margin boost, happier clients.

Finally, two glimpses of hope:

1. The dart team [is maintaining a sample of a Dart HTTP server](https://github.com/dart-lang/samples/tree/master/server/google_apis)  that uses Firestore and that features `googleapis` and the `shelf` packages among others;
2. [The last Google's IO featured a "Dart Full-stack" talk](https://youtu.be/r8rVm4-RJJM) which honestly got my hopes up for something "more" in the future.

I'm just guessing Google's trying to figure out if such an investment is worth it... and I dare say it might be. I'd like to contribute in some ways, but I really don't know how to do that.

**Comment by gmcdowell** [comment]
A lonely upvote to Google in what is otherwise an ignored feature request.
Surely even Google can recognize the value in a truly single code base platform/framework.
Dart has so many benefits over Typescript it is not funny.
What do we developers need to do to get your attention on this?
