### ISSUE TITLE
Repeatition invoked when starting

### ISSUE THREAD

**Issue by Oskang09** [firebase/firebase-functions#329]
![image](https://user-images.githubusercontent.com/15674107/46532054-022d2300-c8d2-11e8-95ad-c5e67b66a114.png)

Like image given, all logging has repeated. but when hot reloading call won't be like this, also `firebase deploy` won't be like this. Is that any problem in `firebase serve`? If didn't wrong only occurs after update to newest 5.0.0

* firebase-tools 5.0.0

**Comment by laurenzlong** [comment]
@Oskang09 This is expected behavior, I'm assuming those lines are `console.log`s you have in your code. When the emulator is emulating 3 functions, it actually loads index.js 3 times (once for each functions), so that's why the logs are getting printed 3 times. if you wanted to emulate only one function, you can run `firebase serve --only functions:<functionName>`
