### ISSUE TITLE
Custom google "decode" function causing issues with non-google usage

### ISSUE THREAD

**Issue by ryanhornberger** [firebase/firebase-functions#331]
Hey guys!

The 'decode' function of the ['https.ts'](https://github.com/firebase/firebase-functions/blob/17beb774163130220f2463bc4ae1d83878b45711/src/providers/https.ts#L394) file is throwing unnecessary errors.

This may be related to [this Issue](https://github.com/firebase/firebase-functions/issues/316)

Given that the comment above the 'decode' function reads

```
/**
 * Decodes our special format for JSON into native types.
 * This is exposed only for testing.
 */
/** @internal */
```

I believe the right course of action here is bypass the decode function entirely for all use-cases outside of Google's own use cases. 

Thus my suggestion is to modify [this line](https://github.com/firebase/firebase-functions/blob/17beb774163130220f2463bc4ae1d83878b45711/src/providers/https.ts#L457). It currently reads as

```
const data = decode(req.body.data);
```

but may just as easily, and without exceptions, read:

```
const data = req.body.data;
```

I decided not to write a pull-request here as I don't understand where else such a change might have an impact in the broader Google ecosystem.

An alternative is to allow us to indicate we'd rather do our own encoding/decoding.

Regardless, an exception fires on the client when the content I am passing contains an "@type" key in an object such as the below example when the @type key is not related to internal google formats. 

In this example, the @type key is related to JsonLd content.

### Version info

**firebase-functions:**
master
**firebase-tools:**
n/a
**firebase-admin:**
n/a

### Test case

Server Side

```
export const example = functions.https.onCall(async (data, context) => {
  return {
      "url": "https://www.google.com",
      "name": "Google",
      "description": "Test 123",
      "@context": "http://schema.org",
      "@type": "WebSite"
   }
}
```

Client Side

```
const result = await firebase.functions().httpsCallable('example')({})
```

### Steps to reproduce

- Create the above 'example' onCall function and deploy it
- Use the firebase client to make the above client side call
- Obtain error "Error: Data cannot be decoded from JSON: ...."

### Were you able to successfully deploy your functions?

Yes, not a problem

### Expected behavior

the response does not error out and the const 'result' is populated with

```
  {
      "url": "https://www.google.com",
      "name": "Google",
      "description": "Test 123",
      "@context": "http://schema.org",
      "@type": "WebSite"
   } 
```

### Actual behavior

An exception on the client side is thrown "Error: Data cannot be decoded from JSON: ...."

**Comment by laurenzlong** [comment]
Hi there, thanks for the feedback. The documentation `This is exposed only for testing.` does not mean that this method is only useful for internal Google purposes, it means that the function is exported from the module so that it can be imported by a unit test. But the function itself is still intended for all users. 

The `@type` field key is reserved so that we can support many languages of client SDKs (Java, C++, Swift, Objective C, etc.) Because some of those languages have types that do not exist in JavaScript, we use `@type` to store the type information so that it is not lost when the response is sent to the client app. 

To support your use case, I would suggest writing the entire thing in a string, instead of a object, and then parsing it back into an object in your client app. 

E.g.
```
export const example = functions.https.onCall(async (data, context) => {
  return JSON.stringify({
      "url": "https://www.google.com",
      "name": "Google",
      "description": "Test 123",
      "@context": "http://schema.org",
      "@type": "WebSite"
   });
}
```

Client Side

```
const result = await firebase.functions().httpsCallable('example')({})
JSON.parse(result)
```
