### ISSUE TITLE
Server Error. self signed certificate in certificate chain

### ISSUE THREAD

**Issue by MilesArtemius** [firebase/firebase-functions#332]
### Version info

**firebase-functions:** latest (just updated)

**firebase-tools:** latest (just updated)

**firebase-admin:** __

When deploying functions to server, self-signed certificate chain server error appears:
i  deploying functions
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (1.02 KB) for uploading
!  functions: Upload Error: Server Error. self signed certificate in certificate chain

Error: Server Error. self signed certificate in certificate chain

**Comment by MilesArtemius** [comment]
[firebase-debug.log](https://github.com/firebase/firebase-functions/files/2471238/firebase-debug.log)
Added debug log.

**Comment by laurenzlong** [comment]
Hi there, the error is coming from Google Cloud Storage, the CLI tries to upload your functions source code there before deploying your functions. It appears that `HTTP REQUEST PUT https://storage.googleapis.com/gcf-upload-us-central1-bae2bc63-d93a-4c9c-bec6-e4cfbf7b3e4a/77e5cd09-9cef-44bd-b0e3-5347faf0a788.zip` is giving the error, because it is not working with your local set up. I'm not sure that self-signed certificate chain is a supported feature of Google Cloud Storage. You can investigate further by looking at the [public tracker for Cloud Storage](https://issuetracker.google.com/savedsearches/559782) and potentially file a feature request.
