### ISSUE TITLE
Suggestion: Peer Dependencies to allow minor revisions

### ISSUE THREAD

**Issue by dustensalinas** [firebase/firebase-functions#342]
` "peerDependencies": {
    "firebase-admin": "~6.0.0"
  }, `

Suggestion:
`6.x` or the like.

Reasoning: Minor incremental updates such as the current state of
`
    "firebase-admin": "^6.1.0",
    "firebase-functions": "^2.1.0",
`
This is causing undo warnings and potential library conflicts.

**Comment by motin** [comment]
Example of warning omitted:
```
npm WARN firebase-functions@2.1.0 requires a peer of firebase-admin@~6.0.0 but none is installed. You must install peer dependencies yourself.
```

This is with the following package.json contents:
```
$ cat package.json | grep firebase-admin
    "firebase-admin": "^6.3.0",
```

**Comment by thechenky** [comment]
Hi @dustensalinas thanks for the feedback. The reason that we are using `~` instead of a `^` is because historically minor versions of `firebase-admin` that added new types would sometimes break the Functions SDK. I'm still digging into exactly what happened there to see if we can change this to a `^` since I don't think minor versions should be breaking. Stay tuned for updates.

**Comment by thechenky** [comment]
Please see updates and resolution in #354. Closing this out, thanks everyone!
