### ISSUE TITLE
Proxy config for local development

### ISSUE THREAD

**Issue by yavorski** [firebase/firebase-functions#392]
Hi, can we have something like proxy config while developing locally?

Right now if we want to develop locally a web app for example, we need to allow CORS for every function we write.

However when the web app and functions are deployed to production, there is no need for CORS and things just works.

Is this the only possible way to develop locally - to clutter the functions code and allow CORS in them if for example NODE_ENV=development?

It would be nice, if we could have something like a proxy config and just use that in development environment without messing with the functions code?

Please, let me know your thoughts on this.

**Comment by thechenky** [comment]
Hi @yavorski thank you for your feedback. Can you explain your use case better for me? Are you using functions in combination with hosting? Are you specifically needing CORS or is this a step to make something else work? Generally for these types of feature requests we like to direct developers to our [support portal](https://firebase.google.com/support/contact/bugs-features/) which are the best place for feature requests and can be grouped internally to better understand the needs of our developers.

**Comment by yavorski** [comment]
Hi, @thechenky, yes I am using functions in combination with hosting.

In general I am working on web application using `firebase hosting` and `firebase functions`.

What I seek here is the development process to be as close to the production one and without modifying functions to enable CORS in development when this is not needed for production.

The project is scaffolded with `firebase cli` and running with `firebase serve` locally.
However `firebase serve` runs hosting on port 5000 and functions on port 5001.

I also use `app.functions().useFunctionsEmulator('http://localhost:5001')` on the client.

In this situation in order to be able to call functions from the client (web app) (they are on different ports) I need to enable/setup CORS in the cloud function, which is the case I am actually trying to avoid, because it is not needed on the production environment.

Hope this makes more sense.

**Comment by thechenky** [comment]
Hi @yavorski thank you for the detailed explanation! That all makes sense, and I can see how that would make local development more cumbersome, especially since the behavior differs from production. We do need to do some things differently in local environment because hosting and functions are emulated and on different ports as you mentioned, so I see some difficulties with getting this to work without CORS. All that said, I think this is a good feature request and have noted this in our internal tracker. Thanks for your feedback! I'm going to close this out as we don't track feature requests in Github.

Internal bug reference: 123317649

**Comment by mbleigh** [comment]
Hi @yavorski just so you know, when the Hosting and Cloud Functions emulators are both running, any Hosting rewrites will be emulated locally. For instance if I have a `firebase.json` like:

```json
{
  "hosting": {"rewrites": [{"source": "**", "function": "app"}]}
}
```

and I have `index.js` of:

```js
exports.app = functions.https.onRequest((req, res) => {
  res.send('no cors here');
});
```

When I run `firebase serve` I can visit `http://localhost:5000/` and the local function will be triggered. You shouldn't need CORS in this case, because you can just point to your rewrites with absolute URLs in your AJAX code.

Does that make sense?
