### ISSUE TITLE
Context before and after changed to possibly undefined in 2.2.0

### ISSUE THREAD

**Issue by 0x80** [firebase/firebase-functions#413]
The upgrade from 2.1.0 to 2.2.0 broke my builds because the Typescript definitions changed `context.before` and `context.after` into possibly undefined.

Seems like it might be a regression of #227

**Comment by 0x80** [comment]
Not a regression, since in #227 the whole context object was possibly undefined. Now it's just the before/after properties.

**Comment by samtstern** [comment]
@0x80 looks like in this commit they were made non-optional:
https://github.com/firebase/firebase-functions/commit/df27316a9e5c8d74f3aedc8fabca066ab9de53c1

So I think this will be fixed in the next release (that commit was 17 days ago, 2.2.0 was 21 days ago).

@thechenky does that sound right?  I am going to close this since the fixing commit is already in but please re-open if there's more to do.
