### ISSUE TITLE
Update dependencies and enable automated updates

### ISSUE THREAD

**Issue by merlinnot** [firebase/firebase-functions#439]
I'm currently working on a feature (#425) and I'm bumping into issues because of outdated dependencies. I'd like to make a PR with dependency updates, so it doesn't decrease readability of a PR with the feature. I'll go ahead and bump all dependencies that are not breaking.

What do you think about enabling [Renovate](https://renovatebot.com) for this repository? Here's a config we could use:

```json
{
  "bumpVersion": "patch",
  "commitMessageAction": "update",
  "rangeStrategy": "bump",
  "rebaseStalePrs": true,
  "recreateClosed": true
}
```

**Comment by merlinnot** [comment]
I can see that some of Firebase repositories use Repository Gardener. Let me know what's your preference and if I can help you somehow.

**Comment by joehan** [comment]
I like the idea of enabling [Repository Gardener](https://github.com/GoogleCloudPlatform/repository-gardener) on this repo. The one snag I see is that we regularly sync this with a private repo, which might complicate things, but as long as we only enable it on the public side, I think it would work. @thechenky, what do you think?

**Comment by thechenky** [comment]
@merlinnot can you give me an example of a Firebase repo that uses this tool?

**Comment by merlinnot** [comment]
Here you go:

https://github.com/GoogleCloudPlatform/repository-gardener
https://github.com/firebase/firebase-js-sdk/pull/1599

**Comment by thechenky** [comment]
Thanks @merlinnot! I talked with the devs maintaining that repo and they suggested they will likely be moving to Renovate. One issue I see with this is that Renovate is paid - so I'll have to get approval and we would have to use the hosted version. This may take some time to do, so I've filed a bug for myself to look into doing this in the future, at which point I'll loop you in. Unfortunately right now, we're pretty swamped with other higher priority work. Thank you again though for your PRs and your proactive involvement in trying to make this repo better! Really appreciate it. 

Internal bug reference: 134178323

I'm going to close out this issue in the meantime since we won't be addressing it in the near future.
