### ISSUE TITLE
3.0.1 not using .runtimeconfig.json

### ISSUE THREAD

**Issue by zanona** [firebase/firebase-functions#476]
I am not sure it's just me but after upgrading to 3.0.1 with `.runtimeconfig.json` file under the functions directory no longer populates values from the file with:

```js
const functions = require('firebase-functions');
console.log(functions.config())
```

```
cd functions-dir
firebase functions:config:get > .runtimeconfig
firebase serve
```

the output is `{}`

but then if I downgrade to `firebase-functions` `3.0.0`, it works without problem.

**Comment by thechenky** [comment]
Hi @zanona I'm assuming you found the resolution to your issue - would you mind sharing it here in case other developers run into the same problem?

**Comment by zanona** [comment]
Hey Diana, unfortunately I haven’t found it. However it seems the issue was
not really the version number. But it is still a mystery to me how
.runtimeconfig.json works since it is still bot populating vars on firebase
serve even with the file in the functions directory.
Is there any specific documentation on how that works? At the moment I take
it’s magic :)

Il giorno lun 17 giu 2019 alle 13:41 Diana Tkachenko <
notifications@github.com> ha scritto:

**Comment by thechenky** [comment]
@zanona Just to clarify - are you having issues on `firebase serve` only? As in, are the config values populated properly in your deployed functions? If it's `firebase serve` that is the problem, then make sure you're using the latest `firebase-tools` version (I recommend 6.12.0 or 7.0.0 if you're not using Node 6), since we've had some emulation issues that have been resolved recently. You can see more info and possibly related issues in this repo: https://github.com/firebase/firebase-tools/issues. Let me know if that resolves your issue.

To answer your general question, we use the `.runtimeconfig.json` file behind the scenes during deployment of functions (and during emulation as well), and this file actually gets uploaded to the GCF runtime and read on start to populate your configs so that you can do `functions.config().mykey` and get the value you set it to using `firebase functions:config:set mykey="some-value"`.

**Comment by zanona** [comment]
Thanks @thechenky. Ok, I believe I have found the issue:

https://github.com/firebase/firebase-functions/blob/860dd00fb81148bd600ffe6b44d9bb6657fd3586/src/config.ts#L85

The location of `.runtimeconfig.json` is not really where the function directory is but instead the root of the packages where firebase tools is running from. I have a monorepo with packages under the `packages` directory, so `./packages/api` is where my functions are. With that said, if moving `.runtimeconfig.json` into `./packages/api/.runtimeconfig.json` will not expand the variables, because I am running `firebase serve` from my root packages at `./`.

The solution in this case was to move `.runtimeconfig.json` into the root package and it now works as expected. This actually makes sense since `firebase serve` enables emulation for web app under `packages/app` as well as `packages/api` so it's sensible it's ran from the root package.

**Comment by thechenky** [comment]
Ah yes, `firebase-functions` will expect the `.runtimeconfig.json` file to be at the root of the project as you correctly determined since it's using a relative path to find it from its own node_modules directory. I'm glad you were able to resolve your issue and also that the mystery has been solved about the `.runtimeconfig.json` file :) I'm going to close this out. If you have any other issues, please don't hesitate to open another issue!
