### ISSUE TITLE
Would this library work a normal node server?

### ISSUE THREAD

**Issue by jQrgen** [firebase/firebase-functions#5]

**Comment by laurenzlong** [comment]
Hey jQrgen, could you elaborate on your question a bit more? What is your use case?

**Comment by jQrgen** [comment]
Hei @laurenzlong i'm wondering if the firebase cloud functions library would work as expected on a heroku-hosted v6.10.0 node.js server or if the hosting provided by firebase is required for the firebase functions node module to work properly.

**Comment by laurenzlong** [comment]
Hey @jQrgen unfortunately, this SDK has to be used with the Google Cloud Functions runtime environment. Otherwise, events happening in your app will not actually trigger the execution of the functions. We have a free tier for Cloud Functions for Firebase, so you can give it a try without paying. 

Note that the Google Cloud Functions runtime environment is different from "Firebase hosting", which hosts static files for your web page. You can absolutely use another solution (such as Heroku) for hosting your html, css, and js files and still use Cloud Functions for Firebase at the same time.
