### ISSUE TITLE
Every function is run twice

### ISSUE THREAD

**Issue by theryan722** [firebase/firebase-functions#584]
### [REQUIRED] Version info

**node:** 8.16.2 (package.json node engine set to 8)

**firebase-functions:** 3.3.0

**firebase-tools:** 7.8.1

**firebase-admin:** 8.6.1

**Firebase (Web Client):** 7.4.0

### [REQUIRED] Test case

Run a callable function (e.g. using var myServerFunction= mainFirebase.functions().httpsCallable('myServerFunction');)

### [REQUIRED] Steps to reproduce

Run a callable function.

### [REQUIRED] Expected behavior

Function gets called and executed once.

### [REQUIRED] Actual behavior

The function is run twice, with the first time instantly returning a 204:
```
Function execution started
Function execution took 23 ms, finished with status code: 204
```
then right after:
```
Function execution started
Functon execution took 1432 ms, finished with status code: 200
```
The second execution runs fine. My logs are filled with tons of the first execution of every function just running and returning a 204.

### Were you able to successfully deploy your functions?

There are no error messages. Deploys work perfectly.

**Comment by samtstern** [comment]
@theryan722 I apologize for the slow response here.  I have a few clarifying questions:

- Is this issue happening to you in production? Does it happen if you deploy a very simple "hello world" callable function or only with your own code?  I am surprised to see a 204 result.
- Can you show a little more of the JavaScript code where you're calling the callable function?

**Comment by mbleigh** [comment]
If you are calling the function from the browser, this is expected behavior because the browser is going to be making a CORS preflight `OPTIONS` request to ensure that the function is willing to serve cross-origin content. This request is automatically handled for you by the wrapping logic of the callable function, so your code doesn't get executed but that is in fact a legitimate and necessary request for a browser to be able to call the function.

**Comment by theryan722** [comment]
Thanks for the clarification, that makes sense. I appreciate the answer, I learned something new as well!

**Comment by antoniooi** [comment]
Will this double our Firebase function **invocation cost**? Another scenario could be that when we have **one project multiple sites** and we prefer to store our cloud functions for different app in different .JS file. To do that, we export all the function signatures in `index.js` -- Would that cause a double invocation as well and will it double the invocation cost? Thanks.

**Comment by mbleigh** [comment]
CORS requires two requests whenever a browser is making a "cross-origin" request. The origin is everything before the path in a URL, so `https://example.com` and `https://subdomain.example.com` are two different origins, but `https://example.com/foo` and `https://example.com/bar` are not.

The browser makes an `OPTIONS` requests *always* for cross-origin network calls except in "basic" cases where there are no custom headers etc. Since callable functions always include an `Authorization` header, they will always trigger a CORS `OPTIONS` request.

**Comment by antoniooi** [comment]
> Since callable functions always include an `Authorization` header, they will always trigger a CORS `OPTIONS` request.

You mean for Https Callable Functions, even though same origin request, it will trigger CORS `OPTIONS` and lead to double invocation costs too? I'm currently running localhost with the latest version of Firebase Emulators, making same origin requests, and it causes double invocations too.

**Comment by mbleigh** [comment]
On localhost different ports are considered different origins.

**Comment by dhstack** [comment]
@mbleigh Is it possible to .then chain Firebase callable functions that have these two responses for CORS reasons? Like if the first response/invocation is a 204 response, in the client code if I add `.then((res) => { console.log(res) })` to the callable function call wouldn't `res` not exist until the second call/invocation that gives the 200 response?

I'm doing something like this and the second function invocation with the expected response of 200 never happens (according to the Firebase logs) so I'm wondering if it's because of CORS.

**Comment by mbleigh** [comment]
The first call is handled by the SDK wrapper without ever executing your code. Technically, the second request is the one that returns the valid response, but the preflight request happens silently in the background before the "real" request is issued. You don't need to worry about "handling" the preflight request on the browser side, the browser does that for you.

**Comment by antoniooi** [comment]
@mbleigh Well, I only worry about the **Invocation Charge**. Although Google offers 2 mil invocations as free quota on Firebase, after the free quota has exceeded, **the charges become doubled due to double invocations**. But do correct me if I'm wrong. Thanks.

**Comment by mbleigh** [comment]
That's correct. One way to avoid the double-invocation charge would be to
connect your callable functions to Firebase Hosting as rewrites and specify
the full URL in the client-side Callable Functions SDK. I'd recommend not
worrying too much about the double-invocations though. Until your app is of
truly enormous scale it's unlikely to be an issue.

**Comment by WillowP** [comment]
> The first call is handled by the SDK wrapper without ever executing your code.

Is this true for `functions.https.onRequest` as well as `functions.https.onCall`? I've noticed that in the `onRequest` functions my code is being executed during the `OPTIONS` request. The only way I could find to prevent this was:

```js
const myFunc = functions.https.onRequest(async (request, response) => {
  response.set("Access-Control-Allow-Origin", "*");
  response.set("Access-Control-Allow-Headers", "Content-Type");

  if (request.method === "OPTIONS") {
    return response.json({});
  }

  // the rest of the function...
}
```

Otherwise the function was getting executed, and failing because the OPTIONS request does not send the full request payload (ie, the body).

**Comment by rikelme** [comment]
> 

Hi Michael,

Can you please elaborate on what would it take to avoid the first "OPTIONS" call? I'm not sure I follow your hint.
It concerns as because it adds an extra ~150-200ms to the function call execution time.

Thanks,
Miro
