### ISSUE TITLE
Error parsing triggers: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by eng-dibo** [firebase/firebase-functions#608]
`tslib` already installed in the same folder with `functions.source`

firebase.json:
```
{
"functions": {    
    "source": "."
  }
}
```

project structure:
|-firebase.json
|-node_nodules
|-dist/firebase/index.js <-- contains the functions

package.json:
```
{
dependencies:{
 "tslib": "^1.10.0",
}
}
```
[repo](https://github.com/goblins-tech/almogtama3)
[deployment details ](https://github.com/goblins-tech/almogtama3/runs/394959227)

![047d080a-8909-479c-87b4-734cad74b764](https://user-images.githubusercontent.com/57308531/73092729-cf9fa300-3ee5-11ea-8e47-06145ab23768.png)

**Comment by laurenzlong** [comment]
@eng-dibo sorry for the late response, I assume you probably already resolved the issue, but it's likely due to the fact that you need to run "npm install" before deploying. Please feel free to reopen another issue if you're still having trouble, and open the issue in https://github.com/firebase/firebase-tools. This repo is for the SDK, not for deployment issues.
