### ISSUE TITLE
Firebase cloud functions: issue with initializeApp

### ISSUE THREAD

**Issue by sensotix** [firebase/firebase-functions#689]
firebase/firebase-admin-node#602 # [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS 10.15.4
  * Firebase SDK version: 8.12.1
  * Firebase Product: all (auth, database, storage, etc)
  * Node.js version: 10.18.1
  * NPM version: 6.14.5

### [REQUIRED] Step 3: Describe the problem
We use the `firebase-admin` package within Cloud Functions and use a dedicated `lib/firebase.js` module to perform initialization. For some time now, triggers using this library, such as Firestore triggers, do not work anymore. We receive the following error when the trigger executes and reaches the first call of `admin.<something>`:

`Error: The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.`

Detailed investigation pins the problem down to the fact that the [DEFAULT] app is never initialized. But checking `admin.apps.length === 0` is always falsy since there is indeed an app available in the array with the name `__admin__`  

As checking the `apps.length` property is also recommended in the online examples, I suspect the second app has recently been added and most likely refers to changes in the `firebase-functions` module. As a workaround, we've changed the initialization logic to check for the [DEFAULT] app explicitly.

#### Workaround
```
const initialized = admin.apps.some(app => app.name === "[DEFAULT]");

if (!initialized) {
   // call initializeApp(...)
}
```

#### Steps to reproduce:

See code below.

#### Relevant Code:

`lib/firebase.js`
```
const admin = require('firebase-admin');

if (!admin.apps.length) {
  const serviceAccount = require('../service-account-credentials.json');
  const config = JSON.parse(process.env.FIREBASE_CONFIG);

  admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
    databaseURL: config.databaseURL,
  });
}

module.exports = admin;
```

`firestore-triggers/helloWorld.js`
```
const admin = require('../lib/admin');

module.exports = (change, context) => {
  const fs = admin.firestore(); // <--- execution crashes here
  console.log('hello world');
  return null;
}
```

`index.js`
```
exports.helloWorld = functions.region(defaultRegion).firestore.document('hello/{world}').onWrite((change, context) =>
   require('./firestore-triggers/helloWorld')(change, context) // lazy loading trigger
);
````

**Comment by mbleigh** [comment]
I can see how this is a bit confusing, but this is working as intended. [This is the code](https://github.com/firebase/firebase-functions/blob/a001a8537dd9704d1d1c089191ce2ab514d1e3fb/src/apps.ts) that manages the `__admin__` app and it's needed to provide certain capabilities of the `firebase-functions` SDK. Nothing about this has changed recently, but changes in loading order in your code might have started triggering the issue.

In general, since `require()` statements are cached and not executed on repeat, do you need the `if ()` guard at all? You should be able to just call `initializeApp()` and so long as you're only doing it once in that one file it should work fine.

In any case, the workaround you've suggested also seems like a perfectly good way to conditionally initialize, so I'd keep with that if it's working for you.

**Comment by sensotix** [comment]
Thank you @mbleigh, this makes perfect sense and I think you are right regarding loading order. We might have just been lucky before. Thanks also for the caching-hint!

**Comment by konstantinosftw** [comment]
@mbleigh thanks a lot for your workaround, I didn't manage to make it work any other way. Despite `require()`, using `initializeApp()` without the `if` guard was still trying to initialize a new `[Default]` instance.
