### ISSUE TITLE
Value for argument "documentPath" is not a valid resource path. Path must be a non-empty string.

### ISSUE THREAD

**Issue by Omotola28** [firebase/firebase-functions#692]
![image](https://user-images.githubusercontent.com/23417243/82270419-aca16f00-996c-11ea-8d6f-79ea7f8fe0f3.png)

Keep getting same error even if document path is passed as string and it is correct

**Comment by kierandesmond** [comment]
Having the same issue too.

**Comment by ndr** [comment]
Have the same issue also,
In my case, I am trying to create new document with firebase function:
await this.adminFirestore.collection(`users/${uid}/services`).add(productData);
The document is created, but I am receiving this exception

**Comment by laurenzlong** [comment]
@Omotola28 @kierandesmond could you please provide more details?
- What SDK version are you using?
- Are you able to successfully deploy your functions?
- Where are you seeing the error? Is it from the CLI when you deploy? Or in the execution logs from the Firebase Console?

@ndr it seems like your issue is with the firebase-admin SDK, not with the firebase-functions SDK. Please file a issue in https://github.com/firebase/firebase-admin-node

**Comment by Omotola28** [comment]
Hi @laurenzlong 

-  the sdk version the firebase-functions version i am currently using is 3.3.0 
- I am successfully able to deploy the functions but when I test the code that should trigger that cloud function to be executed I get the error above

- The error is seen in the execution logs and not the CLI

**Comment by laurenzlong** [comment]
Thanks @Omotola28! If you're able to deploy the function, then the code in your screenshot is not what's causing the issue. It's probably from a line inside your function that is reading from or writing back to Firestore. It sounds like you're having a similar issue to https://github.com/firebase/firebase-admin-node/issues/320 and there are several possible causes outlined in the thread.

**Comment by kierandesmond** [comment]
The issue in my case was a service outage. Thanks for your help and follow
up.
