### ISSUE TITLE
Why retryConfig is only available for scheduled functions?

### ISSUE THREAD

**Issue by sk-** [firebase/firebase-functions#699]
Currently only scheduled functions have a retry config, however all background functions support retries, see https://firebase.google.com/docs/functions/retries.

Given that the underlying technology for all the background functions is pubsub, it should be straightforward to add the retry config to the other function types.

For us this would simplify our development, as a bunch of our firestore triggers are randomly failing either with a [RST error](https://github.com/googleapis/nodejs-firestore/issues/1023), or with no error at all. And having a consistent way of specifying the retries would be quite nice.

**Comment by sk-** [comment]
This feature is now even more pressing as Cloud Console changed the UI to edit a function and now we are unable to edit them. See https://issuetracker.google.com/u/0/issues/162440541.

`gcloud` is not an option either because it requires to pass the source code of the function.

Please advise if there are any workarounds.

**Comment by sk-** [comment]
@mbleigh any chance this could be prioritized or maybe you could bump the internal issue related to https://issuetracker.google.com/u/0/issues/162440541.

**Comment by stari4ek** [comment]
I'd like to confirm the problem mentioned by @sk- .

There is no way to enable retries for firebase functions using GCP UI now.
When I enable "Retry on failure" for function with "Cloud Firestore" trigger - it requires to re-deploy function using web UI.
Using already deployed source code ("Inline Editor" selected) gives build error (most probably since it expects google cloud function and does not have any magic applied by firebase cli): `Build failed: function.js does not exist; Error ID: 7485c5b6`

So it means there is no way to enable retries **at all**.

**Comment by sk-** [comment]
This should be fixed by #760 and available in the next release of firebase-tools. See https://github.com/firebase/firebase-tools/issues/1734#issuecomment-677761734
