### ISSUE TITLE
Why was all the previous environment variables removed in the node 10 runtime?

### ISSUE THREAD

**Issue by larssn** [firebase/firebase-functions#730]
So our project is pretty dependent on the `GCP_PROJECT` variable, which we use to dynamically switch between our production and test database. I'm reluctant on pulling the trigger on updating to node 10 because of this, since it's just gonna make our workflows more troublesome.

I can't think of a good reason why these were removed. Can anyone clarify?

**Comment by mbleigh** [comment]
They were removed as an effort to maintain consistency across multiple stacks -- specifically Cloud Functions, Cloud Run, and self-hosted Knative services. Unfortunately since the environment variables are reserved we didn't have a way in the Firebase tooling to preserve the old variables.

You should be able to work around this, however, using the `FIREBASE_CONFIG` environment variable which embeds `projectId`:

```js
const projectId = JSON.parse(process.env.FIREBASE_CONFIG).projectId
```
