### ISSUE TITLE
How to fix the following

### ISSUE THREAD

**Issue by JamesVanWaza** [firebase/firebase-functions#749]
When I get this error, what is the right way to fix it? 

<img width="1622" alt="Screen Shot 2020-07-29 at 6 47 37 PM" src="https://user-images.githubusercontent.com/4000076/88861615-56527700-d1cc-11ea-853f-3037b891f88b.png">

**Firebase-Admin**:9.0.0
**Firebase-Functions**: 3.8.0
**Node**:  12.16.3
**NPM**: 6.14.4

**Comment by samtstern** [comment]
@JamesVanWaza I apologize for the super slow response here, I know you probably no longer care about this issue.  This can occur when your emulators don't shut down cleanly, which means there's a `tmp` file left in place that makes one Emulator Suite think that another copy is already running.

Since this is not a `firebase-functions` issue I'm going to close it but if you're still having this issue please file a new GitHub issue on the `firebase-tools` repo and I am happy to take a look!
