### ISSUE TITLE
IP Address Always Google Internal Data Center

### ISSUE THREAD

**Issue by patburke234** [firebase/firebase-functions#771]
I am writing a Firebase Function, specifically for Dialogflow chatbot fulfillment. I am having trouble getting an accurate client IP address regardless of how I am testing it.

I've seen on various posts the various ways to read client IP, but they are either undefined or an internal Google IP from one of their data centers.

I've tried reading:
```

"x-forwarded-for" header
req.connection.remoteAddress
req.ip
req.ips (collection of all of them, there is only ever 1 in the collection)
```

**node:** v10.16.1
**firebase-functions:** 3.11
**firebase-tools:** 6.14.5
**firebase-admin:** 8.11.0

firebase --version => 8.6.0

###Test case

Any request to my Firebase Functions app, locally or deployed, lists  a Google Internal Data Center IP and not the client's IP address. 

Example: I am currently in Italy with IP Address: 151.61.40.0
The firebase function received IP Address: 64.233.172.71 (Canada, Internal Google ISP)

###Steps to reproduce
Make an HTTP Request to a Firebase Function.

###Expected behavior

The above IP addresses should be the client's IP address and not the Google internal data center IP. See example above.

###Actual behavior

I get a Google internal IP address half way across the world. See example above.

### Were you able to successfully deploy your functions?
Yes

**Comment by mbleigh** [comment]
Hi, I think this is the expected behavior. When querying the Google Assistant, the end-user device does not connect directly to your service -- rather, the request is mediated by Google's servers. Unless there is a way to configure Dialogflow to forward this information, there is no way to expose it in a Cloud Function.

You might want to post a question on the [Dialogflow mailing list](https://groups.google.com/forum/#!forum/dialogflow-enterprise-edition-users) since that's who might be able to change this, but my guess is that it's meant to be this way on purpose.

**Comment by patburke234** [comment]
Okay thank you for the prompt response.
