### ISSUE TITLE
Cannot build just after initializing functions

### ISSUE THREAD

**Issue by lucasriondel** [firebase/firebase-functions#782]
If you try to run a `firebase init functions`, then go inside the `functions` folder and run a `yarn build`, `tsc` outputs errors. You have to add the following line to your `tsconfig.json`, inside `compilerOptions`: `"typeRoots": ["node_modules/@types"]`

**Comment by saevarb** [comment]
I am having this issue as well and I don't understand how this issue can be 3 months old without any input from the developers. This literally means that when you create a new project, initialize functions and try to build it, nothing works. This is an extremely poor experience.

**Comment by samtstern** [comment]
Before I go on I want to say that while it may sometimes work, `yarn` is fundamentally not supported with Cloud Functions. You should use `npm` if you want to be sure that your production functions will run as they do locally.

First of all here's the environment I am working with:
```
$ node --version
v10.19.0
$ firebase --version
9.3.0
```

Then in a totally empty directory I ran `firebase --init functions`:
```
$ firebase init functions

     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  /private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.y9KDotv4

Before we get started, keep in mind:

  * You are currently outside your home directory


=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

? Please select an option: Don't set up a default project

=== Functions Setup

A functions directory will be created in your project with a Node.js
package pre-configured. Functions can be deployed with firebase deploy.

? What language would you like to use to write Cloud Functions? TypeScript
? Do you want to use ESLint to catch probable bugs and enforce style? Yes
✔  Wrote functions/package.json
✔  Wrote functions/.eslintrc.js
✔  Wrote functions/tsconfig.json
✔  Wrote functions/tsconfig.dev.json
✔  Wrote functions/src/index.ts
✔  Wrote functions/.gitignore
? Do you want to install dependencies with npm now? Yes

> protobufjs@6.10.2 postinstall /private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.y9KDotv4/functions/node_modules/protobufjs
> node scripts/postinstall

npm notice created a lockfile as package-lock.json. You should commit this file.
added 378 packages from 275 contributors and audited 378 packages in 21.728s

46 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...
i  Writing gitignore file to .gitignore...

✔  Firebase initialization complete!
```

Now I'll try to build:
```
$ cd functions/
$ npm run build

> functions@ build /private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.y9KDotv4/functions
> tsc

src/index.ts:1:1 - error TS6133: 'functions' is declared but its value is never read.

1 import * as functions from "firebase-functions";
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! functions@ build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the functions@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/samstern/.npm/_logs/2021-02-04T14_28_00_869Z-debug.log
```

Ok that's a lint error, so let me change `functions/src/index.ts` to this:
```ts
import * as functions from "firebase-functions";

export const helloWorld = functions.https.onRequest((request, response) => {
  functions.logger.info("Hello logs!", {structuredData: true});
  response.send("Hello from Firebase!");
});
```

Now I'll try again, no build issues:
```
$ npm run build

> functions@ build /private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.y9KDotv4/functions
> tsc
```

So I am not able to reproduce this issue and I don't think there's actually a problem here if you use `npm`

**Comment by lucasriondel** [comment]
@samtstern Maybe the documentation should specify that when you're using typescript, you *have to* use `npm` ? I'm sure this has caused issues to many users, and this would save their time. And I have to agree with the points raised by @saevarb too.

**Comment by taeold** [comment]
I'm unable to reproduce the original issue where I have to make following changes to the `tsconfig.json`:

```
...
compilerOptions: "typeRoots": ["node_modules/@types"]
```

`yarn build` command just worked out of the box on my machine. Here's my setup for reference:

```
firebase-tools 9.10.2
typescript 3.9.9
firebase-functions 0.2.3
node v14.15.4
```

It's be several months since this issue was opened, and maybe recent versions of various dependencies we have fixes the issue.

To respond to some other points raised in this issue:

1. Automatically runs `npm`

I'm surprised to hear this. When I run `firebase init`, it asks me whether it would like to run `npm`.  I entered "No" and moved on.

Maybe you meant that all the scripts we pre-fill in `package.json` is wired up to run `npm`? Feels like defaulting to `npm` is a reasonable choice, but feel free to contribute if you like more flexibility there. You'd need to make the changes in https://github.com/firebase/firebase-tools/tree/master/templates/init/functions/typescript.
 
2. Need to change the `engine`

Unfortunately, I don't see a good way around this. Firebase Functions uses the value set in the `engine` attribute to choose the runtime of the function to deploy. In `npm`, `engine` attribute isn't strictly checked against your environment whereas `yarn` does enforce it. I don't think this is necessarily bad - afterall, it's probably better for your dev setup to be similar to the environment where your function will be deployed. Guessing that you think this is a bad default? Mind if I ask why?

3. Easily mess things up

Would like to hear more. I'm not sure what you mean exactly here.

**Comment by taeold** [comment]
Now that I think about it, we can probably improve the initialized `engine` field to be a bit smarter by looking at the current version of node on the developer machine. Nodejs runtime in Cloud Function is a bit limited, but for the majority of the cases, we could probably fill in {10,12,14} without too much trouble.

I can file a FR in https://sourcegraph.com/github.com/firebase/firebase-tools. Let me know if any of you guys would like to contribute!

**Comment by taeold** [comment]
Filed a FR in https://github.com/firebase/firebase-tools on the engine issue.

Besides not being able to reproduce the `tsconfig` issue described in the original report, I think this covers most of the frustrations coming from using `yarn` in place of `npm`. Let me know if I missed anything by re-opening the issue!
