### ISSUE TITLE
Adding roles to projectid@appspot.gserviceaccount.com may break permissions?

### ISSUE THREAD

**Issue by johnparn** [firebase/firebase-functions#792]
### Related issues

None what I know of. And I'm not sure this is specific to Firebase Functions.

### [REQUIRED] Version info

**node: v12.19.0**

**firebase-functions: 3.11.0**

**firebase-tools: 8.12.0**

**firebase-admin: 9.2.0**

### [REQUIRED] Steps to reproduce

I've experienced this problem in two separate Firebase projects.

Setup a firebase project using Firebase Auth, Cloud Firestore and Firebase functions. 

Add functions for `auth.onCreate` and `auth.onDelete`. As a user is created in Firebase Auth `auth.onCreate` is triggered and adds some data to Cloud Firestore. When deleting a user `auth.onDelete` is triggered, deleting data in Cloud Firestore. This worked flawlessly for more than 5 months. 

Yesterday, in order to backup Cloud Firestore, I needed to add role permissions to the account projectid@appspot.gserviceaccount.com. The roles were _Storage Admin_ and _Cloud Datastore Import Export Admin_ to be specific. I was following the solution described here:https://firebase.google.com/docs/firestore/solutions/schedule-export#configure_access_permissions

Before adding the roles, the IAM in the Google Cloud console didn't list any roles associated with the projectid@appspot.gserviceaccount.com account. So I added the roles to the account using Google Cloud console and clicked save. Notice, I hadn't deployed any new functions at this moment, just added the roles.

### [REQUIRED] Expected behavior

Adding new roles should add permissions without breaking current permissions.

### [REQUIRED] Actual behavior

Right after adding the roles to the account I could spot `Error: 7 PERMISSION_DENIED: Missing or insufficient permissions` in the log of both `auth.onCreate` and `auth.onDelete`, neither could read or write to Cloud Firebase. The solution was to add the FirebaseAdmin role to the projectid@appspot.gserviceaccount.com. 

I verified this in a separate project with the same setup.

Why did the functions work for months without projectid@appspot.gserviceaccount.com having the FirebaseAdmin role and why did the permissions to access Cloud Firestore stop working after adding roles to it?

**Comment by taeold** [comment]
Hi @johnparn. Thanks for reporting the issue and sorry we did not get back to you earlier.

As you already mentioned, your Firebase Function instances runs w/ service account <projectid>@appspot.gserviceaccount.com by default. In most cases, when this service account is setup, it is given an "Editor" role, and with the change you made it probably lost other Firebase-related permissions needed to operate.

See this document for more info: https://cloud.google.com/functions/docs/concepts/iam#runtime_service_accounts.

I'm unsure why that SA did not show up in your IAM console page. It must have been properly configured since it was running w/o a problem for 5 months, but perhaps there was something that went awry w/ the initial project setup process that prevented you from seeing the SA in your IAM list.

I'm glad the issue was resolved. If you want to prevent something like this from happening again, you could try to setup a specific SA for your function instances, and you can use `.runWith({ serviceAccount: XXX})` annotation on your function to customize it. But in most cases, you wouldn't have to do something like this.

Feel free to re-open the issue if you are having other issues.
