### ISSUE TITLE
Deploying functions with failurePolicy should not always require --force

### ISSUE THREAD

**Issue by rbruggem** [firebase/firebase-functions#798]
### Related issues

The comment explains how it should work.

https://github.com/firebase/firebase-functions/issues/425#issuecomment-485037960

### [REQUIRED] Version info

**node:** 10.18.1

**firebase-functions:** 3.11.0

**firebase-tools:** 8.12.0

 8.12.0

**firebase-admin:** 8.6.0

### [REQUIRED] Test case

`firebase deploy --only functions:THEFUNCTION` errors with:
`Error: Pass the --force option to deploy functions with a failure policy`

### [REQUIRED] Steps to reproduce

Add `failurePolicy: { retry: {} }` to an existing function which does not have a failure policy set.

### [REQUIRED] Expected behavior

Running `firebase deploy --only functions:THEFUNCTION` would deploy the function successfully without the use of `--force`.

### [REQUIRED] Actual behavior

`Error: Pass the --force option to deploy functions with a failure policy`

### Were you able to successfully deploy your functions?

Only with `--force` which is not ideal to have in a CICD pipeline.

**Comment by joehan** [comment]
Hey @rbruggem , I believe that this is working as intended ATM. Trying to set a failurePolicy on a function that does not have one yet should trigger this warning or require --force. The idea behind this is that setting a failure policy can cause functions to be retired many times, which can be dangerous if your functions perform expensive operations or are not built to be idempotent.

**Comment by inlined** [comment]
Reopening for continued discussion. The claim that this is WAI suggested that we only require --force or a confirmation when first adding a failure policy to the function. The confirmation is actually happening every time a function with a failure policy is used. Will raise with the team.

**Comment by breno-bicycle** [comment]
In my opinion it should have different flags to enable the auto delete or the failurePolices. 

My team has a CD process that uses the `firebase deploy` to auto deploy affected cloud functions. We started using the --force, but it happened that a code with a bugs deleted some cloud functions automatically. So we removed the --force and added the --non-interactive. Now we are having issues with the failurePolicies. Our default is not having the failure policies, and when we do, is because we are certain that the function is idempotent. so, is there a way to enable the `failurePolicies` and still not enable the auto deletion?
