### ISSUE TITLE
Deploy fails during preinstall check, throwing "command not found: only-allow" error. Node 8 to 10 related.

### ISSUE THREAD

**Issue by John-Shortland-PikiTech** [firebase/firebase-functions#833]
### [REQUIRED] Version info

**node:** 10.21.0

**firebase-functions:** 3.13.0

**firebase-tools:** 9.0.1

**firebase-admin:** 9.4.2

### [REQUIRED] Test case

To re-deploy existing functions after 15 Dec 2020.

### [REQUIRED] Steps to reproduce

- Upgraded Node JS dependency from 8 to 10 in package.json file
- Upgraded Firebase plan from Spark to Blaze in Firebase Console and Google Cloud Platform
- Deployed functions using `firebase deploy --only functions`

### [REQUIRED] Expected behavior

Functions to be deployed successfully.

### [REQUIRED] Actual behavior

"**_command not found: only-allow_**" error thrown.
```
i  functions: uploading functions in project: createJournal(us-central1)
i  functions: updating Node.js 10 function createJournal(us-central1)...
⚠  functions[createJournal(us-central1)]: Deployment error.
Build failed: > functions@1.0.0 preinstall /workspace
> npx only-allow pnpm

npx: installed 25 in 2.215s
command not found: only-allow
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@1.0.0 preinstall: `npx only-allow pnpm`
npm ERR! Exit status 1
```

### Were you able to successfully deploy your functions?

No, when I ran `firebase deploy`, I get a "**_command not found: only-allow_**" error. It was working yesterday but not today?!

**Comment by inlined** [comment]
As far as I can tell, this is an issue with one of your dependencies, not any code maintained by Google.

Your error is getting emitted by Google Cloud Build, which is running `npm install --production <archive of your package>` to create a Docker image. `npm install` automatically calls several scripts, such as `preinstall`, `prepare`, `postinstall` etc. 

As far as I can tell, some node module (for some unknown reason) wants to make sure it is only installed with [pnpm](https://pnpm.js.org/) instead of npm or yarn (see [only-allow's documentation](https://www.npmjs.com/package/only-allow)). The not found error is probably happening because the package listed `only-allow` as a dev dependency but Cloud Build only installs production modules.

You can find out which node module is doing this with:

```
find . -name "package.json" | xargs grep -l "npx only-allow pnpm"
```

You can stop using that module, convince the maintainer to drop the only-allow check, convince the maintainer to make only-allow a production dependency, or fork the module if you cannot convince the maintainer. That would be my order of recommendation.
