### ISSUE TITLE
Allow to sample tracing

### ISSUE THREAD

**Issue by sk-** [firebase/firebase-functions#837]
### Related issues

None that I could find.

### [REQUIRED] Version info

**node:** 12

**firebase-functions:** 3.11.0

**firebase-tools:** 9.1.0

**firebase-admin:** 9.4.2

### [REQUIRED] Test case

N/A

### [REQUIRED] Steps to reproduce

Enable tracing in google cloud console and see how all requests get traced.

### [REQUIRED] Expected behavior

Enabling tracing should not flood the traces with spans not generated by us.

### [REQUIRED] Actual behavior

If one enables google cloud tracing, then you get flooded by meaningless traces, as they don't have enough information.

These traces have the `/component` part set to either `AppServer` or `HTTP load balancer`.

Furthermore these spans consume much more than the free quota. In our case we end up paying quite a significant amount.

Instead of tracing all of the requests, we should be able to configure the sample ratio via a config option. Alternatively you could change the pricing to not count spans coming from your own systems.

### Were you able to successfully deploy your functions?

Yes

**Comment by inlined** [comment]
The "HTTP Load balancer" trace is from Google's load balancer and the AppServer is the last-mile load balancer/server. If you add tracing to your function your spans will be parented to those traces and you'll be able to see, for example, the cost of Google's routing infrastructure and the cost of your cold starts. This is by design.

These traces are treated specially by Google. Because they come from our infrastructure we automatically apply a(n undocumented) rate limit to them. We also give them to you free of charge.
