### ISSUE TITLE
What is the exact node 14 runtime version number?

### ISSUE THREAD

**Issue by laurentpayot** [firebase/firebase-functions#849]
As asked in https://github.com/firebase/firebase-tools/pull/2903#issuecomment-752710890:

> What version number exactly is the node 14 runtime ? This info is needed the to install the same node version on the local dev machine.

**Comment by samtstern** [comment]
@laurentpayot I asked some GCP folks and it seems that this is intentionally not specified, since it may change over time as the GCF runtime gets critical patches.  The best thing to do would be to run a quick "hello world" function in production and then check the node version at runtime.

I'm also told you can figure out the exact version by looking at the open-source buildpacks but truth be told I have not figured out how:
https://github.com/GoogleCloudPlatform/buildpacks/tree/main/builders/gcf

**Comment by laurentpayot** [comment]
> The best thing to do would be to run a quick "hello world" function in production and then check the node version at runtime.

Thanks @samtstern, yes I will probably add a `console.log` of [process.version](https://nodejs.org/api/process.html#process_process_version) somewhere.
