### ISSUE TITLE
Property 'firebaseArgs' implicitly has type 'any', because its get accessor lacks a return type annotation.

### ISSUE THREAD

**Issue by AgungLaksana** [firebase/firebase-functions#852]
I have this error when trying to recomplie my typescript code using `tsc`

node_modules/firebase-functions/lib/apps.d.ts:33:21 - error TS7033: Property 'firebaseArgs' implicitly has type 'any', because its get accessor lacks a return type annotation.

33         private get firebaseArgs();

I use this dependecies:
"firebase-admin": "^9.4.2",
"firebase-functions": "^3.13.1"

and currently  using engines node 14 and Firebase CLI 9.2.2

how to solve this issue?

**Comment by mikgross** [comment]
Same here after uploading firebase-functions this morning.

node_modules/firebase-functions/lib/apps.d.ts:33:21 - error TS7033: Property 'firebaseArgs' implicitly has type 'any', because its get accessor lacks a return type annotation.
33         private get firebaseArgs();

@AgungLaksana did you solve this ?

**Comment by mikgross** [comment]
A workaround that made the trick:
delete `node_modules`, delete `packages-lock.json`, run `npm install`.

**Comment by AgungLaksana** [comment]
i can solve the problem by update the firebase CLI and firebase function to
the latest version

**Comment by inlined** [comment]
Closing since this works at HEAD
