### ISSUE TITLE
Wrong Types for UserRecord

### ISSUE THREAD

**Issue by cupcakearmy** [firebase/firebase-functions#875]
* Operating System version: macOS Big Sur
  * Firebase SDK version: 9.5.0 (firebase-admin)
  * Firebase Product: Auth
  * Node.js version: v14.16.0
  * NPM version: 1.22.10

### [REQUIRED] Step 3: Describe the problem

Wrong types in `firebase-admin/lib/auth/index.d.ts` for `UserRecord`.

Attributes like `phoneNumber` or `photoURL` are marked as `string | undefined` while in reality they are `string | null`.
I thought I was going crazy 😅

#### Steps to reproduce:

Create a dummy on auth hook and console log some attributes that do not exist.

#### Relevant Code:

```
import { fns } from '../lib/admin'

export const onUserCreate = fns.auth.user().onCreate(async (user) => {
  console.log(user.photoURL) // Should be undefined but is null
})

```

**Comment by cupcakearmy** [comment]
I opened the issue here because the types are defined in the admin sdk

**Comment by joehan** [comment]
Thanks for raising this, it seems like this should be changed to match how they are defined in the admin sdk. Opened https://github.com/firebase/firebase-functions/pull/876 to fix this - just need to make sure that we are ok with this since its technically a breaking change for users that are specifically checking for `if (userRecord.field != null)

**Comment by cupcakearmy** [comment]
> Thanks for raising this, it seems like this should be changed to match how they are defined in the admin sdk. Opened #876 to fix this - just need to make sure that we are ok with this since its technically a breaking change for users that are specifically checking for `if (userRecord.field != null)`

@joehan awesome seeing a quick fix for this ❤️
Normlly I'd agree that this would be a breaking change, however if people are relying on != null it means unpredictable code and bugs in production (as in my case) so I would suggest not waiting to long. Breaking changes only apply if the current state is working IMO 🙂

**Comment by inlined** [comment]
You're correct that the proper falsey behavior would have been undefined. Unfortunately after triage we decided that we cannot change the falsey behavior without a major version bump because it would break unknown numbers of customers code. We will strongly consider taking this fix in the next major version of the SDK, but this fix doesn't by itself warrant creating a major version.

**Comment by cupcakearmy** [comment]
You are right, I thought you were updating the typings. Updating the actual behavior is a breaking change of course. Thank you all 🎉

**Comment by inlined** [comment]
Actually, per @hiranya911 's comment, the Admin SDK is using `null`. `firebase-functions` painstakingly either imports or recreates the Admin SDK's behavior, so this is WAI unless/until the Admin SDK changes its behavior.
