### ISSUE TITLE
Allow dynamic function exports

### ISSUE THREAD

**Issue by cedvdb** [firebase/firebase-functions#90]
I'm trying to make a library that'd allow one to use decorators instead of the standard API.

Example:

```javascript
import { https } from "firebase-functions";

export function Https(path: string) {
    return function (target: Object, propertyKey: string, desc: TypedPropertyDescriptor<any>){
	let original = desc.value;
	desc.value = function(...args: any[]) {
		https.onRequest(original);
	};
    }
}
```

To have this 

```javascript
class Test {
	@Https('newmessage')
	newMessage(req: any, res: any){
		res.send('test');
	}

	@Trigger(Trigger.onWrite)
        @Ref('message')
	onNewMessage(req: any, res: any){
		
	}
}
```
Instead of this

```javascript
export let newmessage =  functions.https.onRequest(onNewMessage);
onNewMessage(req: any, res: any){
	res.send('test');
}
```

The problem is that it won't work since it seems like firebase analyses the exported vars. I'd be nice if it allowed object like so:

```javascript
firebase.setFunctionsObject({ varname : 'nesmessage' , handler: fn })
```

**Comment by laurenzlong** [comment]
Hey @cedvdb , I'm closing this since it is not following the issue template (which is designed to ensure that Github issues are used for bug reports, not feature requests like this).

It sounds like you can accomplish what you want by doing:
```
module.exports = {
   newsmessage: fn
};
```

If I misinterpreted what you said, and you actually mean something else, can you file a support ticket so your feature request can be triaged appropriately?  https://firebase.google.com/support/contact/bugs-features/
