### ISSUE TITLE
Should minInstances show up continuously in GC Console? 

### ISSUE THREAD

**Issue by robertedjones** [firebase/firebase-functions#976]
### [REQUIRED] Version info

**node:** 14

**firebase-functions:** 3.15.6

**firebase-tools:** 9.18.0

**firebase-admin:** 9.11.1

### [REQUIRED] Steps to reproduce

set runtime options on function: 

```
runtimeOpts = {
  timeoutSeconds: 60,
  memory: '1GB',
  minInstances: 1,
}
```

### [REQUIRED] Expected behavior

Google Cloud Console Active Instances Chart should always show at least 1 instance is active and cold start time should be eliminated.

### [REQUIRED] Actual behavior

It seems like the instances are not being kept active and cold start times continue.

In the Cloud Console I can see the setting has updated and displays `minInstances: 1` but looking at the chart it looks like there isn't always at least 1 instance available: 

![image](https://user-images.githubusercontent.com/10974474/133679633-4ca505c6-5fbe-4cb2-a1f0-5880c372774c.png)

### Were you able to successfully deploy your functions?
Yes

**Comment by taeold** [comment]
@robertedjones Hi Robert! I've looked internally for an answer, and it looks like the Google Cloud Functions team are working on correcting the active instance count metrics. They should be corrected by the time min instance feature goes into beta/GA, in the meantime your min instance setting should be working as expected.

It sounds like you are still experiencing cold starts. While min instance should help reduce the number of cold starts, it won't completely eliminate them if your workload requires more instances than configured in your min instances. If you are suspicious that something is going wrong, please go ahead and reach out to [Google Cloud support](https://cloud.google.com/functions/docs/getting-support) - the support teeam should be able to look into your project-specific setup and logging to diagnose any issues.

I'm closing the ticket since this isn't a bug related to code being developed in this repository.
